/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Landmark, CityConfig } from './utils';

// -------------------------------------------------------------
// 0. HARIPUR (KPK, PAKISTAN) LANDMARKS
// -------------------------------------------------------------
export const LANDMARKS_HARIPUR: Landmark[] = [
  {
    id: 'khanpur-dam',
    name: 'Khanpur Dam & Lake',
    urduName: 'خانپور ڈیم و جھیل',
    placeId: 'ChIJb6F0X8nn3jgRo5Gq-jVqIkg',
    lat: 33.8052,
    lng: 72.9345,
    altitude: 580,
    markerAltitude: 25,
    heading: 320,
    tilt: 52,
    camAltitude: 850,
    camRange: 2200,
    camTilt: 55,
    camHeading: 320,
    category: 'Turquoise Lake & Water Sports Paradise',
    urduCategory: 'فیروزی جھیل و واٹر اسپورٹس ایڈونچر',
    description: 'A breathtaking turquoise-blue reservoir built on the Haro River, famous across Pakistan for cliff diving, paragliding, jet-skiing, boat cruises, and world-renowned red blood orange orchards.',
    urduDescription: 'دریائے ہارو پر واقع دلکش فیروزی جھیل، جو واٹر اسپورٹس، پیراگلائیڈنگ، جیٹ اسکیئنگ اور لذیذ خانپور کے مالٹوں کے باغات کی وجہ سے دنیا بھر میں مشہور ہے۔',
    highlights: ['Cliff Diving & Jet Ski Adventures', 'Emerald Water of Haro River', 'Annual Water Sports Festival', 'Famed Red Blood Orange Orchards'],
    iconName: 'waves',
    pinColor: '#0284C7',
    glyph: '⛵',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M2 20a6 6 0 0 0 12 0 6 6 0 0 0 10 0M2 14a6 6 0 0 0 12 0 6 6 0 0 0 10 0"/></svg>'
  },
  {
    id: 'tarbela-dam',
    name: 'Tarbela Dam & Reservoir',
    urduName: 'تربیلا ڈیم و آبی ذخیرہ',
    placeId: 'ChIJ56bE09m-3jgRD-7r7Lg8V0o',
    lat: 34.0875,
    lng: 72.6980,
    altitude: 480,
    markerAltitude: 35,
    heading: 30,
    tilt: 50,
    camAltitude: 950,
    camRange: 3200,
    camTilt: 52,
    camHeading: 30,
    category: 'World’s Largest Earth-Filled Dam',
    urduCategory: 'دنیا کا سب سے بڑا مٹی کا بند',
    description: 'A colossal engineering wonder built across the mighty Indus River, Tarbela Dam is the world’s largest earth and rock-filled dam, powering the nation with 4,888 MW hydropower and immense spillways.',
    urduDescription: 'دریائے سندھ پر تعمیر شدہ دنیا کا سب سے بڑا مٹی کا بند، جو پاکستان کا سب سے بڑا ہائیڈرو پاور اور آبپاشی کا لائف لائن منصوبہ ہے۔',
    highlights: ['World’s Largest Earth-Filled Dam', 'Mighty Indus River Gorge', 'Massive Giant Spillway Cascades', '4,888 MW Hydroelectric Power'],
    iconName: 'zap',
    pinColor: '#2563EB',
    glyph: '⚡',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/></svg>'
  },
  {
    id: 'jaulian-monastery',
    name: 'Jaulian Buddhist Monastery',
    urduName: 'جولیاں بدھ مت خانقاہ و سٹوپا',
    placeId: 'ChIJc9x1-83n3jgRQ2n6f4u4b38',
    lat: 33.7607,
    lng: 72.8719,
    altitude: 560,
    markerAltitude: 15,
    heading: 45,
    tilt: 55,
    camAltitude: 720,
    camRange: 900,
    camTilt: 55,
    camHeading: 45,
    category: 'UNESCO World Heritage & Ancient Gandhara',
    urduCategory: 'یونیسکو کا عالمی ثقافتی ورثہ و قدیم گندھارا',
    description: 'An exceptionally preserved 2nd-century CE Buddhist hilltop university and monastery in the ancient Taxila-Haripur basin, featuring intact stucco Buddha statues, votive stupas, and ancient monastic living quarters.',
    urduDescription: 'یونیسکو کا عالمی ثقافتی ورثہ، دوسری صدی عیسوی کی بدھ مت درسگاہ جہاں قدیم سٹوپا اور مجسمے آج بھی محفوظ ہیں۔',
    highlights: ['UNESCO World Heritage Site', 'Ancient 2nd-Century Stucco Sculptures', 'Hilltop Panoramic Monastic Ruins', 'Ancient Meditation Cells'],
    iconName: 'landmark',
    pinColor: '#D97706',
    glyph: '🏛️',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><line x1="3" y1="21" x2="21" y2="21"/><line x1="5" y1="21" x2="5" y2="10"/><line x1="9" y1="21" x2="9" y2="10"/><line x1="15" y1="21" x2="15" y2="10"/><line x1="19" y1="21" x2="19" y2="10"/><path d="M2 10h20L12 3z"/></svg>'
  },
  {
    id: 'harkishan-garh-fort',
    name: 'Harkishan Garh Fort',
    urduName: 'قلعہ ہرکشن گڑھ (بانی ہری پور قلعہ)',
    placeId: 'ChIJq87v2_bn3jgRoK1kYF6R5c0',
    lat: 33.9972,
    lng: 72.9331,
    altitude: 530,
    markerAltitude: 20,
    heading: 180,
    tilt: 60,
    camAltitude: 680,
    camRange: 800,
    camTilt: 60,
    camHeading: 180,
    category: 'Historic 1822 Citadel & City Genesis',
    urduCategory: 'تاریخی ۱۸۲۲ء کا قلعہ و بانیِ ہری پور',
    description: 'The historic fortress built in 1822 by General Hari Singh Nalwa during the Sikh Empire which gave birth to Haripur. Enclosed by massive 4-meter thick stone ramparts and the original four city gates.',
    urduDescription: '۱۸۲۲ء میں سکھ جرنیل ہری سنگھ نلوہ کا تعمیر کردہ تاریخی قلعہ جس کے گرد موجودہ شہر ہری پور بسایا گیا تھا۔',
    highlights: ['Birthplace of Modern Haripur City', 'Massive Historic Stone Ramparts', 'City Center Cultural Heritage'],
    iconName: 'shield',
    pinColor: '#DC2626',
    glyph: '🏰',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2l8 4v6c0 5.5-3.8 10.7-8 12-4.2-1.3-8-6.5-8-12V6l8-4z"/></svg>'
  },
  {
    id: 'university-of-haripur',
    name: 'University of Haripur',
    urduName: 'جامعہ ہری پور',
    placeId: 'ChIJN20R7vLn3jgRs7gG8E7eM3c',
    lat: 33.9774,
    lng: 72.9126,
    altitude: 520,
    markerAltitude: 15,
    heading: 90,
    tilt: 55,
    camAltitude: 680,
    camRange: 950,
    camTilt: 55,
    camHeading: 90,
    category: 'Premier Academic & Research Campus',
    urduCategory: 'ہزارہ کی مرکزی یونیورسٹی و جدید ریسرچ کیمپس',
    description: 'A premier public research university of Khyber Pakhtunkhwa spread over an expansive green campus, driving regional advancement in computer science, agricultural biotechnology, and natural sciences.',
    urduDescription: 'ہزارہ ڈویژن کی صفِ اول کی پبلک یونیورسٹی، جو جدید تحقیق، ٹیکنالوجی اور اعلیٰ تعلیم کا مرکزی ادارہ ہے۔',
    highlights: ['Premier Research University of Hazara', 'Expansive Green Academic Campus', 'Hub of Agricultural & Tech Innovation'],
    iconName: 'graduation-cap',
    pinColor: '#059669',
    glyph: '🎓',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M22 10v6M2 10l10-5 10 5-10 5z"/><path d="M6 12v5c3 3 9 3 12 0v-5"/></svg>'
  },
  {
    id: 'sarai-saleh',
    name: 'Sarai Saleh Heritage & Baoli',
    urduName: 'سرائے صالح و تاریخی باؤلیاں',
    placeId: 'ChIJb6F0X8nn3jgRo5Gq-jVqIkx',
    lat: 33.9683,
    lng: 72.9983,
    altitude: 545,
    markerAltitude: 15,
    heading: 240,
    tilt: 55,
    camAltitude: 680,
    camRange: 850,
    camTilt: 55,
    camHeading: 240,
    category: 'Ancient Silk Route Caravanserai & Stepwell',
    urduCategory: 'قدیم کاروان سرائے، شاہراہِ ریشم و تاریخی باؤلی',
    description: 'An ancient caravanserai and trading post dating back centuries, featuring historical stepwells (Baolis), colonial-era brick railway station, and serene freshwater streams fed by the foothills.',
    urduDescription: 'قدیم تجارتی گزرگاہ، تاریخی کاروان سرائے، اور شیر شاہ سوری کے دور کی پانی کی یادگار باؤلیاں۔',
    highlights: ['Historic Silk Route Caravanserai', 'Centuries-old Historical Baolis (Stepwells)', 'Colonial Era Railway Junction', 'Freshwater Stream Meadows'],
    iconName: 'compass',
    pinColor: '#7C3AED',
    glyph: '🏺',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><polygon points="16.24 7.76 14.12 14.12 7.76 16.24 9.88 9.88 16.24 7.76"/></svg>'
  },
  {
    id: 'bhamala-stupa',
    name: 'Bhamala Buddhist Stupa',
    urduName: 'بھمالہ اسٹوپا و وادی ہارو',
    placeId: 'ChIJXb7a1eXn3jgRuR8n9t7X3v0',
    lat: 33.8340,
    lng: 72.9780,
    altitude: 560,
    markerAltitude: 18,
    heading: 310,
    tilt: 55,
    camAltitude: 720,
    camRange: 950,
    camTilt: 55,
    camHeading: 310,
    category: 'Cruciform Stupa & Archaeological Treasure',
    urduCategory: 'نادر کراس نما اسٹوپا و مہا پری نروان مقام',
    description: 'A rare cross-shaped Gandhara stupa near Khanpur Dam where archaeologists unearthed the world’s oldest sleeping Buddha statue (Maha Pari-Nirvana), dating back to the 3rd to 5th centuries CE.',
    urduDescription: 'خانپور جھیل کے کنارے نادر کراس نما گندھارا اسٹوپا جہاں دنیا کے سب سے قدیم سوئے ہوئے بدھ کا مجسمہ دریافت ہوا۔',
    highlights: ['Rare Cruciform Buddhist Architecture', 'Discovery Site of Giant Sleeping Buddha', 'Picturesque Haro River Valley Setting'],
    iconName: 'monument',
    pinColor: '#B45309',
    glyph: '🗿',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M3 21h18M5 21V7l7-4 7 4v14M9 10v11M15 10v11"/></svg>'
  },
  {
    id: 'haripur-central-bazaar',
    name: 'Saddar Bazaar & Chapli Kebab Chowk',
    urduName: 'صدر بازار و چپلی کباب چوک',
    placeId: 'ChIJq87v2_bn3jgRoK1kYF6R5c1',
    lat: 33.9995,
    lng: 72.9350,
    altitude: 520,
    markerAltitude: 15,
    heading: 140,
    tilt: 58,
    camAltitude: 640,
    camRange: 750,
    camTilt: 58,
    camHeading: 140,
    category: 'Vibrant Bazaar & Culinary Epicenter',
    urduCategory: 'روایتی ہزاری چپلی کباب، منڈی و ثقافتی مرکز',
    description: 'The culinary heartbeat of Haripur, famed nationwide for authentic sizzled Hazara Chapli Kebabs, freshly plucked red blood oranges (Malta), Tarbela Mahseer fish, and bustling spice alleys.',
    urduDescription: 'ہری پور کا تجارتی و روایتی مرکز، جو اصلی ہزاری چپلی کباب، تازہ تربیلا فش، اور لذیذ پھلوں کی منڈیوں سے سجا ہے۔',
    highlights: ['Crispy Authentic Hazara Chapli Kebabs', 'Fresh Tarbela Mahseer & Rohu Fish', 'Famous Red Blood Orange Stalls', 'Historic Spice and Silk Alleys'],
    iconName: 'utensils',
    pinColor: '#E11D48',
    glyph: '🥘',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M18 2v20M6 2v7a3 3 0 0 0 6 0V2M9 9v13"/></svg>'
  },
  {
    id: 'makhniyal-ridge',
    name: 'Makhniyal Ridge & Pine Lookout',
    urduName: 'مکھنیال پہاڑی سلسلہ و پائن فاریسٹ',
    placeId: 'ChIJb6F0X8nn3jgRo5Gq-jVqIkm',
    lat: 33.8820,
    lng: 73.0850,
    altitude: 1100,
    markerAltitude: 20,
    heading: 250,
    tilt: 52,
    camAltitude: 1350,
    camRange: 2100,
    camTilt: 52,
    camHeading: 250,
    category: 'Panoramic Mountain Ridge & Pine Forests',
    urduCategory: 'بلند و بالا چیڑ کے جنگلات و مسحور کن نظارے',
    description: 'A spectacular mountain ridge road weaving through pine forests on the crest between Haripur and Margalla, offering breathtaking vistas overlooking Khanpur Lake and terrace farms below.',
    urduDescription: 'بلند و بالا چیڑ کے جنگلات پر مشتمل خوبصورت پہاڑی درہ جہاں سے نیچے خانپور جھیل اور دور تک وادی کا مسحور کن منظر دکھائی دیتا ہے۔',
    highlights: ['Lush Evergreen Himalayan Pine Trees', 'Dramatic Bird’s Eye View of Khanpur Lake', 'Pleasant Cool Mountain Climate'],
    iconName: 'mountain',
    pinColor: '#15803D',
    glyph: '🌲',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="m8 3 4 8 5-5 5 15H2L8 3z"/></svg>'
  },
  {
    id: 'chajjian-waterfalls',
    name: 'Chajjian Waterfalls & Springs',
    urduName: 'چھجیاں قدرتی آبشار و جھرنے',
    placeId: 'ChIJXb7a1eXn3jgRuR8n9t7X3v1',
    lat: 34.0200,
    lng: 73.0700,
    altitude: 750,
    markerAltitude: 20,
    heading: 340,
    tilt: 55,
    camAltitude: 950,
    camRange: 1300,
    camTilt: 55,
    camHeading: 340,
    category: 'Hidden Gorge & Natural Cascade',
    urduCategory: 'خفیہ پہاڑی گھاٹی اور شفاف چشموں کا جھرنا',
    description: 'A secluded cascading freshwater waterfall nestled inside a lush rocky gorge near Haripur, attracting hikers and families seeking crisp mountain spring waters and untouched natural serenity.',
    urduDescription: 'ہری پور کی سرسبز پہاڑیوں کے درمیان قدرتی جھرنا اور صاف شفاف چشمے، جو فطرت سے پیار کرنے والوں کی پسندیدہ تفریح گاہ ہے۔',
    highlights: ['Fresh Mountain Spring Cascades', 'Serene Rocky Canyon Retreat', 'Popular Eco-Tourism & Hiking Trail'],
    iconName: 'droplet',
    pinColor: '#0891B2',
    glyph: '💧',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2.69l5.66 5.66a8 8 0 1 1-11.31 0z"/></svg>'
  },
  {
    id: 'sirikot-gandgar',
    name: 'Sirikot & Gandgar Mountains',
    urduName: 'سریکوٹ و سلسلہ کوہ گنڈگر',
    placeId: 'ChIJ56bE09m-3jgRD-7r7Lg8V0p',
    lat: 34.0600,
    lng: 72.7800,
    altitude: 1050,
    markerAltitude: 25,
    heading: 200,
    tilt: 52,
    camAltitude: 1400,
    camRange: 2400,
    camTilt: 52,
    camHeading: 200,
    category: 'Historic Mountain Range & Indus Overlook',
    urduCategory: 'تاریخی پہاڑی چوٹیاں اور دریائے سندھ کا نظارہ',
    description: 'The legendary Gandgar mountain range rising dramatically beside the Indus River, known for its strategic ridges, rich Hazara folklore, crisp mountain air, and dramatic sunrise panoramas.',
    urduDescription: 'دریائے سندھ کے کنارے واقع تاریخی و پرشکوہ پہاڑی سلسلہ، جس کی چوٹیوں سے تربیلا جھیل اور دور تک وادیوں کا دلکش نظارہ نظر آتا ہے۔',
    highlights: ['Rugged Mountain Peaks & Canyons', 'Overlook of Mighty Indus River', 'Rich Hazara & Gandgar Folklore'],
    iconName: 'mountain-snow',
    pinColor: '#4B5563',
    glyph: '⛰️',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="m8 3 4 8 5-5 5 15H2L8 3z"/><path d="M4 14l4-4 3 3 4-4"/></svg>'
  },
  {
    id: 'hattar-industrial-zone',
    name: 'Hattar Special Economic Zone',
    urduName: 'حطار اسپیشل اکنامک زون',
    placeId: 'ChIJN20R7vLn3jgRs7gG8E7eM3d',
    lat: 33.8600,
    lng: 72.8500,
    altitude: 490,
    markerAltitude: 15,
    heading: 110,
    tilt: 55,
    camAltitude: 750,
    camRange: 1800,
    camTilt: 55,
    camHeading: 110,
    category: 'Industrial Powerhouse of KPK & CPEC Corridor',
    urduCategory: 'خیبر پختونخوا کا سب سے بڑا انڈسٹریل زون و سی پیک',
    description: 'The economic powerhouse of Khyber Pakhtunkhwa featuring hundreds of manufacturing units, pharmaceutical plants, and green engineering complexes against the scenic backdrop of the Margalla foothills.',
    urduDescription: 'خیبر پختونخوا کا سب سے بڑا صنعتی حب اور سی پیک کا اہم ترین تجارتی مرکز جو خطے کی معیشت کی شہ رگ ہے۔',
    highlights: ['Largest Industrial Zone in KPK', 'Crucial Node on CPEC Route', 'Nestled Along Scenic Green Foothills'],
    iconName: 'factory',
    pinColor: '#475569',
    glyph: '🏭',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M2 20a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8l-7 5V8l-7 5V4a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2Z"/><path d="M17 18h1"/><path d="M12 18h1"/><path d="M7 18h1"/></svg>'
  }
];

// -------------------------------------------------------------
// 1. SAN FRANCISCO LANDMARKS
// -------------------------------------------------------------
export const LANDMARKS_SAN_FRANCISCO: Landmark[] = [
  {
    id: 'john-mclaren-park',
    name: 'John McLaren Park',
    placeId: 'ChIJ67-gn-5-j4ARcyjzTqE8ZdU',
    lat: 37.7183,
    lng: -122.4172,
    altitude: 100,
    altitudeCorrection: 80,
    heading: 330,
    tilt: 58,
    camAltitude: 300,
    camRange: 1000,
    camTilt: 58,
    camHeading: 330,
    category: 'Scenic Hilltop Park & Trails',
    description: 'San Francisco’s second-largest park featuring over 312 acres of rugged rolling hills, redwood groves, Philosopher’s Way trail, and panoramic vistas.',
    highlights: ['Second Largest Park in San Francisco', 'Philosopher’s Way Scenic Trail', 'Sweeping 360° Bay and City Views'],
    iconName: 'mountain',
    pinColor: '#059669',
    glyph: '🌲',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M8 3l4 8H5l4-8zM14 9l4 8h-7l3-8zM10 17v5"/></svg>'
  },
  {
    id: 'golden-gate-park',
    name: 'Golden Gate Park',
    placeId: 'ChIJY_dFYHKHhYARMKc772iLvnE',
    lat: 37.7694,
    lng: -122.4862,
    altitude: 60,
    altitudeCorrection: 40,
    heading: 260,
    tilt: 58,
    camAltitude: 350,
    camRange: 1200,
    camTilt: 58,
    camHeading: 260,
    category: 'Urban Park & Conservatory',
    description: 'A 1,017-acre urban oasis stretching from the Haight to the Pacific Ocean, home to world-class museums, gardens, and bison paddocks.',
    highlights: ['1,017 Acres of Public Parklands', 'Historic Conservatory of Flowers', 'Japanese Tea Garden & de Young'],
    iconName: 'tree',
    pinColor: '#10B981',
    glyph: '🌳',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22v-6M8 10a4 4 0 0 1 8 0 3.5 3.5 0 0 1 2.5 5.5 3 3 0 0 1-2.5 3.5H8a3 3 0 0 1-2.5-3.5A3.5 3.5 0 0 1 8 10z"/></svg>'
  },
  {
    id: 'golden-gate',
    name: 'Golden Gate Bridge',
    placeId: 'ChIJw____96GhYARCVVwg5cT7c0',
    lat: 37.8199109,
    lng: -122.4785598,
    altitude: 25,
    altitudeCorrection: 10,
    heading: 215,
    tilt: 60,
    camAltitude: 350,
    camRange: 1400,
    camTilt: 60,
    camHeading: 215,
    category: 'Iconic Suspension Bridge',
    description: 'The world-renowned International Orange suspension bridge spanning the 1-mile strait between San Francisco and Marin County.',
    highlights: ['International Orange Color', 'Art Deco Tower Elements', 'Marin Headlands Lookout'],
    iconName: 'bridge',
    pinColor: '#EA580C',
    glyph: '🌉',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M2 18h20M4 18V8l8-5 8 5v10M8 12v6M16 12v6"/></svg>'
  },
  {
    id: 'alcatraz',
    name: 'Alcatraz Island',
    placeId: 'ChIJI09XaRWBhYARF65xWugonBg',
    lat: 37.8269775,
    lng: -122.4229555,
    altitude: 25,
    altitudeCorrection: 10,
    heading: 135,
    tilt: 60,
    camAltitude: 200,
    camRange: 800,
    camTilt: 60,
    camHeading: 135,
    category: 'Historic Island & Prison',
    description: 'Former maximum-security federal penitentiary situated on an offshore island surrounded by the turbulent currents of San Francisco Bay.',
    highlights: ['Cellhouse Audio Tour', 'First West Coast Lighthouse', 'Bird Sanctuary Gardens'],
    iconName: 'prison',
    pinColor: '#0D9488',
    glyph: '🏝️',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2a10 10 0 1 0 10 10A10 10 0 0 0 12 2Zm0 18a8 8 0 1 1 8-8 8 8 0 0 1-8 8Z"/><path d="M12 6v12M6 12h12"/></svg>'
  },
  {
    id: 'lombard-street',
    name: 'Lombard Street Crooked Section',
    placeId: 'EiZMb21iYXJkIFN0cmVldCwgU2FuIEZyYW5jaXNjbywgQ0EsIFVTQSIuKiwKFAoSCZetgavdgIWAEayywt2XCy_EEhQKEgkhAGkAbZqFgBH_rXbwZxNQSg',
    lat: 37.8021389,
    lng: -122.4187401,
    altitude: 60,
    altitudeCorrection: 45,
    heading: 275,
    tilt: 62,
    camAltitude: 160,
    camRange: 450,
    camTilt: 62,
    camHeading: 275,
    category: 'Scenic Switchback Street',
    description: 'Known as the "Crookedest Street in the World," featuring eight hairpin turns framed by vibrant manicured hydrangeas on Russian Hill.',
    highlights: ['8 Hairpin Switchback Turns', 'Manicured Hydrangea Terraces', 'Russian Hill Russian Heritage Views'],
    iconName: 'road',
    pinColor: '#D97706',
    glyph: '🌸',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="6" cy="19" r="2.5"/><path d="M8.5 19h7a4 4 0 0 0 0-8H8.5a4 4 0 0 1 0-8h7"/><circle cx="18" cy="3" r="2.5"/></svg>'
  },
  {
    id: 'coit-tower',
    name: 'Coit Tower',
    placeId: 'ChIJAQAAQIyAhYARRN3yIQG4hd4',
    lat: 37.8023953,
    lng: -122.4058219,
    altitude: 100,
    markerAltitude: 10,
    altitudeCorrection: 85,
    heading: 260,
    tilt: 65,
    camAltitude: 200,
    camRange: 600,
    camTilt: 65,
    camHeading: 260,
    category: 'Art Deco Vista Tower',
    description: 'A 210-foot Art Deco tower atop Telegraph Hill with 360-degree views of the city and bay, famous for Depression-era fresco murals.',
    highlights: ['Telegraph Hill Summit', '1934 Public Works of Art Murals', '360° Panoramic Observation Deck'],
    iconName: 'tower',
    pinColor: '#E11D48',
    glyph: '🗼',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M6 22h12M9 22V6l3-4 3 4v16M9 12h6M10 7h4"/></svg>'
  },
  {
    id: 'ferry-building',
    name: 'The Ferry Building',
    placeId: 'ChIJWTGPjmaAhYARxz6l1hOj92w',
    lat: 37.795441216344145,
    lng: -122.39361320870182,
    altitude: 70,
    markerAltitude: 75,
    altitudeMode: 'RELATIVE_TO_GROUND',
    altitudeCorrection: 55,
    heading: 300,
    tilt: 65,
    camAltitude: 250,
    camRange: 750,
    camTilt: 65,
    camHeading: 300,
    category: 'Historic Marketplace',
    description: 'A landmark food hall and transit hub located at the foot of Market Street, famous for artisanal vendors and gorgeous waterfront views.',
    highlights: ['Artisanal Food Hall', 'Ferry Terminal Waterfront', 'Historic 245-Foot Clock Tower'],
    iconName: 'ferry',
    pinColor: '#0284C7',
    glyph: '⚓',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="5" r="3"/><line x1="12" y1="22" x2="12" y2="8"/><path d="M5 12H2a10 10 0 0 0 20 0h-3"/></svg>'
  }
];

// -------------------------------------------------------------
// 2. TOKYO LANDMARKS
// -------------------------------------------------------------
export const LANDMARKS_TOKYO: Landmark[] = [
  {
    id: 'meiji-jingu',
    name: 'Meiji Jingu Shrine',
    placeId: 'ChIJoZJ6S72NGGAR0rjOmnbB5LM',
    lat: 35.6763976,
    lng: 139.6993259,
    altitude: 30,
    altitudeCorrection: 15,
    heading: 180,
    tilt: 55,
    camAltitude: 220,
    camRange: 650,
    camTilt: 55,
    camHeading: 180,
    category: 'Imperial Shinto Shrine Forest',
    description: 'A serene Shinto shrine enveloped by a 170-acre evergreen forest of 120,000 trees donated from across Japan in honor of Emperor Meiji.',
    highlights: ['Massive Japanese Cypress Torii Gates', 'Tranquil 170-Acre Sacred Forest', 'Sake Barrel Offerings Wall'],
    iconName: 'shrine',
    pinColor: '#059669',
    glyph: '🌲',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M4 20h16M12 4v16M7 8l5-4 5 4M5 14l7-4 7 4"/></svg>'
  },
  {
    id: 'shibuya-crossing',
    name: 'Shibuya Scramble Crossing',
    placeId: 'ChIJK9EM68qLGGARacmu4KJj5SA',
    lat: 35.6595,
    lng: 139.70055,
    altitude: 25,
    altitudeCorrection: 10,
    heading: 45,
    tilt: 65,
    camAltitude: 180,
    camRange: 450,
    camTilt: 65,
    camHeading: 45,
    category: 'Iconic Urban Intersection',
    description: 'The world’s busiest pedestrian crossing where up to 3,000 people cross simultaneously amidst towering neon billboards and video screens.',
    highlights: ['Massive Multi-Directional Pedestrian Flow', 'Giant Neon Billboards & QFRONT', 'Hachiko Memorial Statue Square'],
    iconName: 'crossing',
    pinColor: '#8B5CF6',
    glyph: '🚶',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="4" r="2"/><path d="M15 22v-4l-3-3 1-6M9 22l3-7-2-3-4 4"/></svg>'
  },
  {
    id: 'roppongi-hills',
    name: 'Roppongi Hills Mori Tower',
    placeId: 'ChIJg5RCD3eLGGAR6dbIHRM98w8',
    lat: 35.660464,
    lng: 139.729249,
    altitude: 150,
    altitudeCorrection: 130,
    heading: 135,
    tilt: 62,
    camAltitude: 320,
    camRange: 750,
    camTilt: 62,
    camHeading: 135,
    category: 'Cultural Modern Skyscraper',
    description: 'A 54-story mixed-use complex housing the Mori Art Museum and the Tokyo City View observation deck overlooking the illuminated skyline.',
    highlights: ['Tokyo City View 360 Observation', 'Mori Art Museum & Modern Sculptures', 'Maman Giant Spider Sculpture Plaza'],
    iconName: 'skyscraper',
    pinColor: '#4F46E5',
    glyph: '🏙️',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="2" width="16" height="20" rx="2"/><line x1="9" y1="6" x2="9" y2="6.01"/><line x1="15" y1="6" x2="15" y2="6.01"/><line x1="9" y1="10" x2="9" y2="10.01"/><line x1="15" y1="10" x2="15" y2="10.01"/><line x1="9" y1="14" x2="9" y2="14.01"/><line x1="15" y1="14" x2="15" y2="14.01"/><line x1="9" y1="18" x2="9" y2="18.01"/><line x1="15" y1="18" x2="15" y2="18.01"/></svg>'
  },
  {
    id: 'tokyo-tower',
    name: 'Tokyo Tower',
    placeId: 'ChIJCewJkL2LGGAR3Qmk0vCTGkg',
    lat: 35.6585805,
    lng: 139.7454329,
    altitude: 120,
    altitudeCorrection: 100,
    heading: 320,
    tilt: 62,
    camAltitude: 350,
    camRange: 850,
    camTilt: 62,
    camHeading: 320,
    category: 'Communications & Observation Tower',
    description: 'The iconic 332.9-meter lattice tower in Minato, inspired by the Eiffel Tower and painted in white and international orange.',
    highlights: ['Main Deck & Top Deck Views', 'Illuminated Diamond Veil Lighting', 'FootTown Museum & Theme Park'],
    iconName: 'tower',
    pinColor: '#EF4444',
    glyph: '🗼',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M6 22h12M9 22V6l3-4 3 4v16M9 12h6M10 7h4"/></svg>'
  },
  {
    id: 'tokyo-station',
    name: 'Tokyo Station (Marunouchi Building)',
    placeId: 'ChIJC3Cf2PuLGGAROO00ukl8JwA',
    lat: 35.6812362,
    lng: 139.7671248,
    altitude: 35,
    altitudeCorrection: 20,
    heading: 270,
    tilt: 60,
    camAltitude: 200,
    camRange: 600,
    camTilt: 60,
    camHeading: 270,
    category: 'Historic Red Brick Terminal',
    description: 'The monumental 1914 red-brick Renaissance terminal designed by Kingo Tatsuno, linking Shinkansen bullet trains across Japan.',
    highlights: ['1914 Taisho Red Brick Facades', 'Restored Classical Domed Ceilings', 'Japan Rail High-Speed Transit Hub'],
    iconName: 'train',
    pinColor: '#D97706',
    glyph: '🚅',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="3" width="16" height="16" rx="2"/><path d="M4 11h16M12 3v8M8 19l-2 3M16 19l2 3"/></svg>'
  },
  {
    id: 'senso-ji',
    name: 'Sensō-ji Temple',
    placeId: 'ChIJ8T1GpMGOGGARDYGSgpooDWw',
    lat: 35.7147651,
    lng: 139.7966553,
    altitude: 20,
    altitudeCorrection: 5,
    heading: 10,
    tilt: 58,
    camAltitude: 180,
    camRange: 550,
    camTilt: 58,
    camHeading: 10,
    category: 'Ancient Buddhist Temple',
    description: 'Tokyo’s oldest temple founded in 645 AD, dedicated to Kannon Bodhisattva and fronted by the grand Kaminarimon Thunder Gate.',
    highlights: ['Kaminarimon Thunder Gate with Giant Lantern', 'Nakamise-dōri Historic Shopping Street', 'Five-Story Pagoda'],
    iconName: 'temple',
    pinColor: '#DC2626',
    glyph: '⛩️',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M2 4h20M4 4v16M20 4v16M2 9h20M9 4v5M15 4v5"/></svg>'
  },
  {
    id: 'tokyo-skytree',
    name: 'Tokyo Skytree',
    placeId: 'ChIJ35ov0dCOGGARKvdDH7NPHX0',
    lat: 35.7100627,
    lng: 139.8107004,
    altitude: 200,
    altitudeCorrection: 180,
    heading: 220,
    tilt: 60,
    camAltitude: 600,
    camRange: 1500,
    camTilt: 60,
    camHeading: 220,
    category: 'Megatall Observation Tower',
    description: 'The tallest structure in Japan and the third-tallest in the world, standing at 634 meters with breathtaking panoramic views over the Kanto Plain.',
    highlights: ['Tembo Deck & Tembo Galleria at 450m', 'Neo-Futuristic Sorakara Design', 'Solamachi Commercial Complex'],
    iconName: 'skytree',
    pinColor: '#06B6D4',
    glyph: '📡',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2v20M8 6h8M6 11h12M7 16h10M5 22h14"/></svg>'
  }
];

// -------------------------------------------------------------
// 3. PARIS LANDMARKS
// -------------------------------------------------------------
export const LANDMARKS_PARIS: Landmark[] = [
  {
    id: 'arc-de-triomphe',
    name: 'Arc de Triomphe',
    placeId: 'ChIJjx37cOxv5kcRPWQuEW5ntdk',
    lat: 48.8737917,
    lng: 2.2950278,
    altitude: 40,
    altitudeCorrection: 25,
    heading: 110,
    tilt: 62,
    camAltitude: 220,
    camRange: 600,
    camTilt: 62,
    camHeading: 110,
    category: 'Neoclassical Triumphal Arch',
    description: 'Commissioned by Napoleon in 1806 to celebrate French military victories, standing prominently at the center of the Place Charles de Gaulle.',
    highlights: ['Champs-Élysées Radial Avenue Axis', 'Tomb of the Unknown Soldier & Eternal Flame', 'Panoramic Rooftop Terrace Over Paris'],
    iconName: 'arch',
    pinColor: '#0284C7',
    glyph: '🏛️',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M4 22V4h16v18M8 22V10a4 4 0 0 1 8 0v12"/></svg>'
  },
  {
    id: 'eiffel-tower',
    name: 'Eiffel Tower (Tour Eiffel)',
    placeId: 'ChIJLU7jZBlu5kcR4PcOOO6p3I0',
    lat: 48.858265597689815,
    lng: 2.2945057569403073,
    altitude: 180,
    markerAltitude: 18,
    altitudeCorrection: 160,
    heading: 140,
    tilt: 62,
    camAltitude: 380,
    camRange: 850,
    camTilt: 62,
    camHeading: 140,
    category: 'Wrought-Iron Lattice Tower',
    description: 'The world-renowned 330-meter wrought-iron lattice monument designed by Gustave Eiffel for the 1889 World’s Fair on the Champ de Mars.',
    highlights: ['Champ de Mars & Trocadéro Panorama', '3 Public Viewing Platforms & Champagne Bar', 'Iconic Sparkling Night Illumination'],
    iconName: 'eiffel',
    pinColor: '#F59E0B',
    glyph: '🗼',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M6 22h12M9 22V6l3-4 3 4v16M9 12h6M10 7h4"/></svg>'
  },
  {
    id: 'musee-orsay',
    name: 'Musée d’Orsay',
    placeId: 'ChIJG5Qwtitu5kcR2CNEsYy9cdA',
    lat: 48.8599614,
    lng: 2.3265614,
    altitude: 30,
    altitudeCorrection: 15,
    heading: 160,
    tilt: 62,
    camAltitude: 220,
    camRange: 600,
    camTilt: 62,
    camHeading: 160,
    category: 'Beaux-Arts Railway Station & Impressionist Museum',
    description: 'Housed in the stunning former Gare d’Orsay railway station on the Left Bank, home to the world’s largest collection of Impressionist masterpieces.',
    highlights: ['Impressionist Masterpieces by Monet & Van Gogh', 'Gare d’Orsay Beaux-Arts Giant Clock', 'Seine Riverfront Promenade'],
    iconName: 'art',
    pinColor: '#059669',
    glyph: '🎨',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><circle cx="12" cy="12" r="6"/><circle cx="12" cy="12" r="2"/></svg>'
  },
  {
    id: 'opera-garnier',
    name: 'Opéra Garnier (Palais Garnier)',
    placeId: 'ChIJOYNm1DBu5kcRZwdtKBzyq6k',
    lat: 48.87197,
    lng: 2.33161,
    altitude: 30,
    altitudeCorrection: 20,
    heading: 340,
    tilt: 62,
    camAltitude: 250,
    camRange: 650,
    camTilt: 62,
    camHeading: 340,
    category: 'Opulent Beaux-Arts Opera House',
    description: 'The 19th-century masterwork of Beaux-Arts architecture renowned for its Grand Marble Staircase, gold leaf salons, and Chagall ceiling.',
    highlights: ['Grand Escalier Marble Staircase', 'Marc Chagall Auditorium Ceiling', 'Historic Phantom of the Opera Setting'],
    iconName: 'theater',
    pinColor: '#3B82F6',
    glyph: '🎭',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M2 10s3-3 10-3 10 3 10 3v11H2V10ZM6 14h12M10 7V4h4v3"/></svg>'
  },
  {
    id: 'sacre-coeur',
    name: 'Sacré-Cœur Basilica (Montmartre)',
    placeId: 'ChIJ442GNENu5kcRGYUrvgqHw88',
    lat: 48.8867046,
    lng: 2.3431043,
    altitude: 75,
    altitudeCorrection: 40,
    heading: 180,
    tilt: 60,
    camAltitude: 300,
    camRange: 750,
    camTilt: 60,
    camHeading: 180,
    category: 'Romano-Byzantine Basilica',
    description: 'The white travertine basilica perched atop the summit of Montmartre, the highest natural elevation in Paris offering sweeping views.',
    highlights: ['Montmartre Hilltop Panorama', 'White Travertine Stone Domes', 'Place du Tertre Artist Square'],
    iconName: 'basilica',
    pinColor: '#10B981',
    glyph: '🕊️',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2a4 4 0 0 0-4 4v16h8V6a4 4 0 0 0-4-4ZM4 12h16M2 22h20"/></svg>'
  },
  {
    id: 'louvre-museum',
    name: 'Louvre Museum & Glass Pyramid',
    placeId: 'ChIJD3uTd9hx5kcR1IQvGfr8dbk',
    lat: 48.8606111,
    lng: 2.337644,
    altitude: 30,
    altitudeCorrection: 15,
    heading: 260,
    tilt: 60,
    camAltitude: 200,
    camRange: 600,
    camTilt: 60,
    camHeading: 260,
    category: 'Historic Palace & Art Museum',
    description: 'The world’s most visited museum, housing masterpieces like the Mona Lisa and Venus de Milo in a former royal fortress with I.M. Pei’s Pyramid.',
    highlights: ['I.M. Pei Glass Pyramid Courtyard', 'Mona Lisa & Winged Victory of Samothrace', 'Historic French Royal Palace Architecture'],
    iconName: 'museum',
    pinColor: '#8B5CF6',
    glyph: '🎨',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M3 21h18M5 21V7l7-4 7 4v14M9 11v10M15 11v10"/></svg>'
  },
  {
    id: 'sainte-chapelle',
    name: 'Sainte-Chapelle (Île de la Cité)',
    placeId: 'ChIJR3122B9u5kcRaCck3PlB9DM',
    lat: 48.85542,
    lng: 2.34502,
    altitude: 40,
    altitudeCorrection: 25,
    heading: 45,
    tilt: 62,
    camAltitude: 220,
    camRange: 550,
    camTilt: 62,
    camHeading: 45,
    category: 'Rayonnant Gothic Royal Chapel',
    description: 'The 13th-century Gothic royal chapel built by King Louis IX to house the Crown of Thorns, celebrated for 1,113 dazzling stained glass scenes.',
    highlights: ['1,113 Stained Glass Biblical Windows', 'Rayonnant Gothic Soaring Vaults', 'Palais de la Cité Royal Medieval Compound'],
    iconName: 'church',
    pinColor: '#8B5CF6',
    glyph: '⛪',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M4 22V8l4-4 4 4v14M12 8l4-4 4 4v14M8 14h8v8H8z"/></svg>'
  },
  {
    id: 'notre-dame',
    name: 'Notre-Dame Cathedral (Île de la Cité)',
    placeId: 'ChIJATr1n-Fx5kcRjQb6q6cdQDY',
    lat: 48.8529682,
    lng: 2.3499021,
    altitude: 50,
    altitudeCorrection: 35,
    heading: 300,
    tilt: 60,
    camAltitude: 220,
    camRange: 650,
    camTilt: 60,
    camHeading: 300,
    category: 'Gothic Masterpiece Cathedral',
    description: 'The medieval Catholic cathedral on the Île de la Cité, famous for French Gothic architecture, flying buttresses, and chimera gargoyles.',
    highlights: ['Île de la Cité Island on the Seine', 'Twin Towers & Restored Spire', 'Medieval Flying Buttresses & Rose Windows'],
    iconName: 'cathedral',
    pinColor: '#6366F1',
    glyph: '⛪',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M4 22V8l4-4 4 4v14M12 8l4-4 4 4v14M8 14h8v8H8z"/></svg>'
  },
  {
    id: 'pantheon-paris',
    name: 'Panthéon',
    placeId: 'ChIJc8mX0udx5kcRWKcjTwDr5QA',
    lat: 48.8462218,
    lng: 2.3464138,
    altitude: 35,
    altitudeCorrection: 25,
    heading: 20,
    tilt: 62,
    camAltitude: 250,
    camRange: 650,
    camTilt: 62,
    camHeading: 20,
    category: 'Neoclassical Monument & Crypt',
    description: 'The grand neoclassical monument in the Latin Quarter housing the national crypt of illustrious figures like Voltaire, Rousseau, and Marie Curie.',
    highlights: ['Latin Quarter Historic Center', 'Neoclassical Dome & Colonnade', 'Foucault’s Pendulum & Crypt'],
    iconName: 'pantheon',
    pinColor: '#EC4899',
    glyph: '🏛️',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M3 20h18M4 20V9l8-5 8 5v11M8 12v8M12 12v8M16 12v8"/></svg>'
  }
];

// -------------------------------------------------------------
// 4. ROME LANDMARKS (Italy)
// -------------------------------------------------------------
export const LANDMARKS_ROME: Landmark[] = [
  {
    id: 'st-peters-basilica',
    name: 'St. Peter’s Basilica (Vatican)',
    placeId: 'ChIJWZsUt2FgLxMRg1KHzXfwS3I',
    lat: 41.9021667,
    lng: 12.4539367,
    altitude: 60,
    altitudeCorrection: 45,
    heading: 90,
    tilt: 60,
    camAltitude: 320,
    camRange: 850,
    camTilt: 60,
    camHeading: 90,
    category: 'Renaissance Papal Basilica',
    description: 'The monumental papal basilica in Vatican City, designed by Michelangelo, Bernini, and Bramante, fronted by St. Peter’s elliptical square.',
    highlights: ['Michelangelo’s Soaring Dome & Pietà', 'Bernini’s St. Peter’s Colonnade Square', 'Baldacchino Bronze Canopy'],
    iconName: 'vatican',
    pinColor: '#EAB308',
    glyph: '⛪',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M4 22V8l4-4 4 4v14M12 8l4-4 4 4v14M8 14h8v8H8z"/></svg>'
  },
  {
    id: 'castel-sant-angelo',
    name: 'Castel Sant’Angelo',
    placeId: 'ChIJ0aTnEYeKJRMRiUF95xwRbDY',
    lat: 41.9030632,
    lng: 12.466276,
    altitude: 35,
    altitudeCorrection: 25,
    heading: 10,
    tilt: 62,
    camAltitude: 240,
    camRange: 650,
    camTilt: 62,
    camHeading: 10,
    category: 'Hadrian’s Fortress & Mausoleum',
    description: 'The towering cylindrical fortress originally built as the Mausoleum of Hadrian on the banks of the Tiber, connected to the Vatican by the Passetto.',
    highlights: ['Ponte Sant’Angelo Angel Statues Bridge', 'Bronze Archangel Michael Summit', 'Passetto di Borgo Secret Escape Corridor'],
    iconName: 'castle',
    pinColor: '#10B981',
    glyph: '🏰',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M2 20h20V8l-3-4-3 4-4-5-4 5-3-4-3 4v12Z"/></svg>'
  },
  {
    id: 'pantheon-rome',
    name: 'Pantheon (Santa Maria Rotonda)',
    placeId: 'ChIJqUCGZ09gLxMRLM42IPpl0co',
    lat: 41.8986108,
    lng: 12.4768729,
    altitude: 30,
    altitudeCorrection: 20,
    heading: 200,
    tilt: 62,
    camAltitude: 220,
    camRange: 550,
    camTilt: 62,
    camHeading: 200,
    category: 'Ancient Roman Temple & Dome',
    description: 'The world’s largest unreinforced concrete dome, built around 126 AD by Emperor Hadrian, featuring the spectacular central Oculus.',
    highlights: ['Unreinforced Concrete Dome & Open Oculus', 'Piazza della Rotonda Fountain', 'Tomb of Renaissance Master Raphael'],
    iconName: 'pantheon',
    pinColor: '#8B5CF6',
    glyph: '🏛️',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M3 20h18M4 20V9l8-5 8 5v11M8 12v8M12 12v8M16 12v8"/></svg>'
  },
  {
    id: 'trevi-fountain',
    name: 'Trevi Fountain (Fontana di Trevi)',
    placeId: 'ChIJ1UCDJ1NgLxMRtrsCzOHxdvY',
    lat: 41.9009325,
    lng: 12.483313,
    altitude: 25,
    altitudeCorrection: 15,
    heading: 170,
    tilt: 65,
    camAltitude: 180,
    camRange: 500,
    camTilt: 65,
    camHeading: 170,
    category: 'Baroque Monumental Fountain',
    description: 'The largest Baroque fountain in Rome, designed by Nicola Salvi showcasing Oceanus in a shell-shaped chariot drawn by seahorses.',
    highlights: ['Oceanus Central Marble Sculpture', 'Historic Coin Tossing Tradition', 'Poli Palace Facade Backdrop'],
    iconName: 'fountain',
    pinColor: '#0284C7',
    glyph: '⛲',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2v8M12 10a4 4 0 0 0-4-4M12 10a4 4 0 0 1 4-4M4 22h16M6 22a6 6 0 0 1 12 0"/></svg>'
  },
  {
    id: 'roman-forum',
    name: 'Roman Forum (Forum Romanum)',
    placeId: 'ChIJ782pg7NhLxMR5n3swAdAkfo',
    lat: 41.8920906,
    lng: 12.4864378,
    altitude: 30,
    altitudeCorrection: 15,
    heading: 310,
    tilt: 60,
    camAltitude: 260,
    camRange: 700,
    camTilt: 60,
    camHeading: 310,
    category: 'Ancient Civic Center Ruins',
    description: 'The ceremonial heart of ancient Rome, surrounded by the ruins of ancient government buildings, temples, basilicas, and triumphal arches.',
    highlights: ['Temple of Saturn & Arch of Septimius Severus', 'Palatine Hill Imperial Palaces', 'Via Sacra Ancient Processional Way'],
    iconName: 'forum',
    pinColor: '#EC4899',
    glyph: '🏛️',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M2 20h20M4 20V6M20 20V6M8 6h8M6 6l6-4 6 4"/></svg>'
  },
  {
    id: 'colosseum',
    name: 'The Colosseum (Flavian Amphitheatre)',
    placeId: 'ChIJrRMgU7ZhLxMRxAOFkC7I8Sg',
    lat: 41.8902102,
    lng: 12.4922309,
    altitude: 40,
    altitudeCorrection: 25,
    heading: 320,
    tilt: 62,
    camAltitude: 250,
    camRange: 650,
    camTilt: 62,
    camHeading: 320,
    category: 'Ancient Roman Amphitheatre',
    description: 'The largest ancient amphitheatre ever built, constructed in 70–80 AD under the Flavian emperors to hold over 50,000 gladiatorial spectators.',
    highlights: ['Hypogeum Underground Chambers', 'Flavian Architectural Arches', 'Arch of Constantine Nearby'],
    iconName: 'colosseum',
    pinColor: '#D97706',
    glyph: '🏟️',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><ellipse cx="12" cy="12" rx="10" ry="6"/><path d="M2 12v4c0 3.3 4.5 6 10 6s10-2.7 10-6v-4"/></svg>'
  }
];

// -------------------------------------------------------------
// 5. NEW YORK CITY LANDMARKS (USA)
// -------------------------------------------------------------
export const LANDMARKS_NEW_YORK: Landmark[] = [
  {
    id: 'statue-of-liberty',
    name: 'Statue of Liberty',
    placeId: 'ChIJPTacEpBQwokRKwIlDXelxkA',
    lat: 40.6892494,
    lng: -74.0445004,
    altitude: 50,
    altitudeCorrection: 35,
    heading: 15,
    tilt: 62,
    camAltitude: 220,
    camRange: 650,
    camTilt: 62,
    camHeading: 15,
    category: 'Colossal Neoclassical Sculpture',
    description: 'A gift of friendship from the people of France dedicated in 1886 on Liberty Island, greeting millions of immigrants in New York Harbor.',
    highlights: ['Copper Torch of Enlightenment', 'Liberty Island Harbor Panorama', 'Seven-Rayed Crown & Broken Shackle'],
    iconName: 'statue',
    pinColor: '#10B981',
    glyph: '🗽',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="6" r="3"/><path d="M12 9v13M8 14l4-2 4 2M9 4l3-2 3 2"/></svg>'
  },
  {
    id: 'one-wtc',
    name: 'One World Trade Center (Freedom Tower)',
    placeId: 'ChIJy7cGfBlawokR5l2e93hsoEA',
    lat: 40.71299968574595,
    lng: -74.01317549214761,
    altitude: 200,
    markerAltitude: 60,
    altitudeCorrection: 180,
    heading: 180,
    tilt: 65,
    camAltitude: 500,
    camRange: 1000,
    camTilt: 65,
    camHeading: 180,
    category: 'Modern Glass Monolith Skyscraper',
    description: 'The tallest building in the Western Hemisphere standing at a symbolic 1,776 feet, crowning Lower Manhattan alongside the 9/11 Memorial.',
    highlights: ['1,776-Foot Glass Monolith Spire', 'One World Observatory 360° Deck', '9/11 Memorial Reflecting Pools'],
    iconName: 'skyscraper',
    pinColor: '#6366F1',
    glyph: '🏙️',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="2" width="16" height="20" rx="2"/></svg>'
  },
  {
    id: 'brooklyn-bridge',
    name: 'Brooklyn Bridge',
    placeId: 'ChIJK3vOQyNawokRXEa9errdJiU',
    lat: 40.7060855,
    lng: -73.9968643,
    altitude: 40,
    altitudeCorrection: 25,
    heading: 230,
    tilt: 60,
    camAltitude: 260,
    camRange: 800,
    camTilt: 60,
    camHeading: 230,
    category: 'Gothic Revival Suspension Bridge',
    description: 'The historic 1883 hybrid cable-stayed suspension bridge connecting Manhattan and Brooklyn across the East River with limestone Gothic arches.',
    highlights: ['Twin Neo-Gothic Stone Towers', 'Elevated Pedestrian Promenade', 'East River & Lower Manhattan Views'],
    iconName: 'bridge',
    pinColor: '#D97706',
    glyph: '🌉',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M2 18h20M4 18V8l8-5 8 5v10M8 12v6M16 12v6"/></svg>'
  },
  {
    id: 'empire-state',
    name: 'Empire State Building',
    placeId: 'ChIJaXQRs6lZwokRY6EFpJnhNNE',
    lat: 40.7484405,
    lng: -73.9856644,
    altitude: 180,
    altitudeCorrection: 160,
    heading: 40,
    tilt: 65,
    camAltitude: 450,
    camRange: 900,
    camTilt: 65,
    camHeading: 40,
    category: 'Art Deco Skyscraper',
    description: 'The 102-story Art Deco masterpiece in Midtown Manhattan, completed in 1931 and standing as a timeless symbol of New York City.',
    highlights: ['86th & 102nd Floor Observatories', 'Art Deco Spire & Tower Lights', 'Midtown Manhattan Skyline Center'],
    iconName: 'skyscraper',
    pinColor: '#0284C7',
    glyph: '🏙️',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="2" width="16" height="20" rx="2"/><line x1="9" y1="6" x2="9" y2="6.01"/><line x1="15" y1="6" x2="15" y2="6.01"/></svg>'
  },
  {
    id: 'central-park',
    name: 'Central Park (Bethesda & The Lake)',
    placeId: 'ChIJ4zGFAZpYwokRGUGph3Mf37k',
    lat: 40.7825547,
    lng: -73.9655834,
    altitude: 35,
    altitudeCorrection: 20,
    heading: 210,
    tilt: 55,
    camAltitude: 350,
    camRange: 1100,
    camTilt: 55,
    camHeading: 210,
    category: 'Urban Green Oasis',
    description: 'An 843-acre green expanse designed by Olmsted and Vaux in the center of Manhattan, offering lakes, woodlands, and grand promenades.',
    highlights: ['Bethesda Terrace & Angel of Waters Fountain', 'Bow Bridge & Central Park Lake', 'The Mall & Literary Walk Elm Canopy'],
    iconName: 'park',
    pinColor: '#059669',
    glyph: '🌳',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2a6 6 0 0 0-6 6c0 3 2 5 6 12 4-7 6-9 6-12a6 6 0 0 0-6-6Z"/></svg>'
  }
];

// -------------------------------------------------------------
// 6. LONDON LANDMARKS (United Kingdom)
// -------------------------------------------------------------
export const LANDMARKS_LONDON: Landmark[] = [
  {
    id: 'buckingham-palace',
    name: 'Buckingham Palace',
    placeId: 'ChIJtV5bzSAFdkgRpwLZFPWrJgo',
    lat: 51.501364,
    lng: -0.14189,
    altitude: 30,
    altitudeCorrection: 15,
    heading: 240,
    tilt: 60,
    camAltitude: 220,
    camRange: 700,
    camTilt: 60,
    camHeading: 240,
    category: 'Royal Administrative Residence',
    description: 'The official London residence of the British monarch, famous for its grand neoclassical facade, State Rooms, and Changing of the Guard.',
    highlights: ['Victoria Memorial Marble Fountain', 'Changing of the Guard Ceremony', 'The Mall Ceremonial Royal Avenue'],
    iconName: 'palace',
    pinColor: '#EF4444',
    glyph: '👑',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M2 20h20V8l-4 4-6-8-6 8-4-4v12Z"/></svg>'
  },
  {
    id: 'big-ben',
    name: 'Big Ben & Palace of Westminster',
    placeId: 'ChIJ2dGMjMMEdkgRqVqkuXQkj7c',
    lat: 51.5007292,
    lng: -0.1246254,
    altitude: 50,
    altitudeCorrection: 35,
    heading: 60,
    tilt: 62,
    camAltitude: 240,
    camRange: 650,
    camTilt: 62,
    camHeading: 60,
    category: 'Gothic Revival Parliament & Clock Tower',
    description: 'The Elizabeth Tower and Great Bell at the north end of the Houses of Parliament, standing majestically along the River Thames.',
    highlights: ['Elizabeth Tower 4-Faced Chime Clock', 'Houses of Parliament Westminster Hall', 'Westminster Bridge Thames Riverfront'],
    iconName: 'clock',
    pinColor: '#D97706',
    glyph: '🕰️',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>'
  },
  {
    id: 'london-eye',
    name: 'The London Eye (Millennium Wheel)',
    placeId: 'ChIJc2nSALkEdkgRkuoJJBfzkUI',
    lat: 51.503424058413444,
    lng: -0.11967606595980002,
    altitude: 60,
    markerAltitude: 15,
    altitudeCorrection: 45,
    heading: 110,
    tilt: 60,
    camAltitude: 250,
    camRange: 650,
    camTilt: 60,
    camHeading: 110,
    category: 'Cantilevered Observation Wheel',
    description: 'The 135-meter observation wheel on the South Bank of the River Thames, providing 360-degree views across Central London.',
    highlights: ['32 Hi-Tech Glass Passenger Capsules', 'South Bank Cultural Promenade', 'Views of Parliament & St Paul’s'],
    iconName: 'wheel',
    pinColor: '#8B5CF6',
    glyph: '🎡',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><path d="M12 2v20M2 12h20M4.93 4.93l14.14 14.14M4.93 19.07l14.14-14.14"/></svg>'
  },
  {
    id: 'the-shard',
    name: 'The Shard London',
    placeId: 'ChIJ03GSCloDdkgRe_s-p2vyvQA',
    lat: 51.5045,
    lng: -0.0865,
    altitude: 160,
    altitudeCorrection: 140,
    heading: 190,
    tilt: 65,
    camAltitude: 420,
    camRange: 850,
    camTilt: 65,
    camHeading: 190,
    category: 'Neo-Futuristic Glass Pyramid Skyscraper',
    description: 'Designed by Renzo Piano, this 72-story glass pyramid is the tallest building in the UK at 309.6 meters overlooking London Bridge.',
    highlights: ['Renzo Piano 11,000 Glass Panes Facade', 'View from The Shard Observation at Level 72', 'London Bridge Historic Quarters'],
    iconName: 'shard',
    pinColor: '#EC4899',
    glyph: '🏙️',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><polygon points="12 2 2 22 22 22"/></svg>'
  },
  {
    id: 'tower-bridge',
    name: 'Tower Bridge London',
    placeId: 'ChIJSdtli0MDdkgRLW9aCBpCeJ4',
    lat: 51.5054564,
    lng: -0.0753565,
    altitude: 40,
    altitudeCorrection: 25,
    heading: 280,
    tilt: 62,
    camAltitude: 250,
    camRange: 750,
    camTilt: 62,
    camHeading: 280,
    category: 'Victorian Bascule & Suspension Bridge',
    description: 'Built between 1886 and 1894, this iconic Victorian Gothic bascule bridge features twin towers connected by high-level walkways.',
    highlights: ['Victorian Gothic Twin Towers', 'Hydraulic Bascule Engine Rooms', 'Glass Floor High-Level Walkway'],
    iconName: 'bridge',
    pinColor: '#0284C7',
    glyph: '🌉',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M2 18h20M4 18V8l8-5 8 5v10M8 12v6M16 12v6"/></svg>'
  }
];

// -------------------------------------------------------------
// 7. BARCELONA LANDMARKS (Spain)
// -------------------------------------------------------------
export const LANDMARKS_BARCELONA: Landmark[] = [
  {
    id: 'park-guell',
    name: 'Park Güell',
    placeId: 'ChIJq0HUUq6ipBIRWM6qGqALmok',
    lat: 41.4144948,
    lng: 2.1526945,
    altitude: 80,
    altitudeCorrection: 50,
    heading: 170,
    tilt: 60,
    camAltitude: 260,
    camRange: 650,
    camTilt: 60,
    camHeading: 170,
    category: 'Gaudí Mosaic Park & Gardens',
    description: 'A whimsical garden complex on Carmel Hill featuring Gaudí’s colorful trencadís ceramic mosaics, serpent benches, and city views.',
    highlights: ['El Drac Mosaic Salamander Staircase', 'Serpentine Mosaic Bench Terrace', 'Hypostyle Hall Stone Columns'],
    iconName: 'park',
    pinColor: '#10B981',
    glyph: '🦎',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2a6 6 0 0 0-6 6c0 3 2 5 6 12 4-7 6-9 6-12a6 6 0 0 0-6-6Z"/></svg>'
  },
  {
    id: 'casa-mila',
    name: 'Casa Milà (La Pedrera)',
    placeId: 'ChIJ1eGKmZOipBIRah43T2Kjn8Q',
    lat: 41.3953,
    lng: 2.1619,
    altitude: 40,
    altitudeCorrection: 25,
    heading: 200,
    tilt: 62,
    camAltitude: 220,
    camRange: 600,
    camTilt: 62,
    camHeading: 200,
    category: 'Modernisme Limestone Masterpiece',
    description: 'Antoni Gaudí’s innovative undulating limestone apartment building with surreal warrior helmet chimneys on its sculptural rooftop terrace.',
    highlights: ['Sculpted Chimney Rooftop Terrace', 'Undulating Natural Stone Facade', 'Gaudí Espai Exhibition in the Attic'],
    iconName: 'building',
    pinColor: '#059669',
    glyph: '🏢',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="2" width="16" height="20" rx="2"/><line x1="9" y1="6" x2="9" y2="6.01"/><line x1="15" y1="6" x2="15" y2="6.01"/></svg>'
  },
  {
    id: 'casa-batllo',
    name: 'Casa Batlló (Passeig de Gràcia)',
    placeId: 'ChIJYUFLSe2ipBIRD04uni940kA',
    lat: 41.3916667,
    lng: 2.165,
    altitude: 35,
    altitudeCorrection: 20,
    heading: 300,
    tilt: 65,
    camAltitude: 200,
    camRange: 550,
    camTilt: 65,
    camHeading: 300,
    category: 'Modernisme Architectural Gem',
    description: 'Gaudí’s fantastical residential remodel on Passeig de Gràcia known as the "House of Bones" with a dragon-back tiled roof.',
    highlights: ['Dragon-Scale Arched Rooftop', 'Skeletal Stone Balconies & Facade', 'Noble Floor Swirling Ceilings'],
    iconName: 'building',
    pinColor: '#8B5CF6',
    glyph: '🐉',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="2" width="16" height="20" rx="2"/></svg>'
  },
  {
    id: 'sagrada-familia',
    name: 'Basílica de la Sagrada Família',
    placeId: 'ChIJk_s92NyipBIRUMnDG8Kq2Js',
    lat: 41.4036299,
    lng: 2.1743558,
    altitude: 90,
    altitudeCorrection: 75,
    heading: 140,
    tilt: 65,
    camAltitude: 320,
    camRange: 700,
    camTilt: 65,
    camHeading: 140,
    category: 'Modernisme Masterpiece Basilica',
    description: 'Antoni Gaudí’s uncompleted magnum opus blending Gothic and Art Nouveau forms, famous for its organic spires and vibrant stained glass.',
    highlights: ['Nativity & Passion Sculpted Facades', 'Forest-like Organic Stone Columns', 'Tower of Jesus Christ Spire'],
    iconName: 'basilica',
    pinColor: '#F59E0B',
    glyph: '🏰',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2v20M8 6h8M6 11h12M7 16h10M5 22h14"/></svg>'
  },
  {
    id: 'arc-triomf-bcn',
    name: 'Arc de Triomf Barcelona',
    placeId: 'ChIJxcogNuOipBIRvlFZYqIlryw',
    lat: 41.391061,
    lng: 2.180632,
    altitude: 30,
    altitudeCorrection: 15,
    heading: 140,
    tilt: 62,
    camAltitude: 220,
    camRange: 600,
    camTilt: 62,
    camHeading: 140,
    category: 'Mudéjar Red Brick Triumphal Arch',
    description: 'Built for the 1888 Universal Exposition in reddish brickwork and Neo-Mudéjar style as the grand gateway to the Ciutadella Park.',
    highlights: ['Neo-Mudéjar Red Brick Masonry', 'Ciutadella Park Palm Promenade', 'Frieze of Barcelona Welcoming Nations'],
    iconName: 'arch',
    pinColor: '#EF4444',
    glyph: '🏛️',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M4 22V4h16v18M8 22V10a4 4 0 0 1 8 0v12"/></svg>'
  }
];

// -------------------------------------------------------------
// 8. SYDNEY LANDMARKS (Australia)
// -------------------------------------------------------------
export const LANDMARKS_SYDNEY: Landmark[] = [
  {
    id: 'darling-harbour',
    name: 'Darling Harbour & Cockle Bay',
    placeId: 'ChIJvwSIiTiuEmsRhszQoBc2SY8',
    lat: -33.87488,
    lng: 151.2009,
    altitude: 30,
    altitudeCorrection: 15,
    heading: 30,
    tilt: 62,
    camAltitude: 220,
    camRange: 750,
    camTilt: 62,
    camHeading: 30,
    category: 'Vibrant Waterfront Precinct',
    description: 'A bustling pedestrian waterside district featuring the ICC Sydney, maritime museums, and illuminated dining along Cockle Bay Wharf.',
    highlights: ['Cockle Bay Waterfront Esplanade', 'Pyrmont Historic Swing Bridge', 'Chinese Garden of Friendship'],
    iconName: 'harbour',
    pinColor: '#8B5CF6',
    glyph: '🏙️',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="2" width="16" height="20" rx="2"/></svg>'
  },
  {
    id: 'sydney-tower-eye',
    name: 'Sydney Tower Eye & SKYWALK',
    placeId: 'ChIJy6BwuD-uEmsRyiRskH1UG-I',
    lat: -33.8705,
    lng: 151.2088,
    altitude: 180,
    altitudeCorrection: 160,
    heading: 80,
    tilt: 65,
    camAltitude: 450,
    camRange: 850,
    camTilt: 65,
    camHeading: 80,
    category: 'Panoramic Observation Tower',
    description: 'Sydney’s tallest structure at 309m, offering 360-degree views from the Pacific Ocean to the Blue Mountains atop Westfield Sydney.',
    highlights: ['360-Degree Observation Deck', 'Outdoor Glass-Floor SKYWALK', 'Highest Viewpoint in Sydney'],
    iconName: 'tower',
    pinColor: '#E11D48',
    glyph: '🗼',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M6 22h12M9 22V6l3-4 3 4v16M9 12h6M10 7h4"/></svg>'
  },
  {
    id: 'sydney-harbour-bridge',
    name: 'Sydney Harbour Bridge (The Coathanger)',
    placeId: 'ChIJ49XqJV2uEmsRPsTAF7eOlGg',
    lat: -33.8523063,
    lng: 151.2107835,
    altitude: 70,
    altitudeCorrection: 50,
    heading: 140,
    tilt: 60,
    camAltitude: 320,
    camRange: 900,
    camTilt: 60,
    camHeading: 140,
    category: 'Steel Through-Arch Bridge',
    description: 'The world’s tallest steel arch bridge (134m), affectionately called "The Coathanger," spanning Port Jackson between the CBD and North Shore.',
    highlights: ['Iconic 134-Meter Steel Arch', 'Pylon Lookout & BridgeClimb', 'Panoramic Views of Opera House'],
    iconName: 'bridge',
    pinColor: '#0D9488',
    glyph: '🌉',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M2 18h20M4 18V8l8-5 8 5v10M8 12v6M16 12v6"/></svg>'
  },
  {
    id: 'sydney-opera-house',
    name: 'Sydney Opera House',
    placeId: 'ChIJ3S-JXmauEmsRUcIaWtf4MzE',
    lat: -33.8567844,
    lng: 151.2152967,
    altitude: 35,
    altitudeCorrection: 20,
    heading: 200,
    tilt: 62,
    camAltitude: 240,
    camRange: 700,
    camTilt: 62,
    camHeading: 200,
    category: 'Expressionist Performing Arts Center',
    description: 'Jørn Utzon’s UNESCO World Heritage masterpiece on Bennelong Point, celebrated for its interlocking white sail-shaped roof shells.',
    highlights: ['White Ceramic Sail Shell Vaults', 'Sydney Harbour Front Waterfront', 'Concert Hall & Opera Theatres'],
    iconName: 'opera',
    pinColor: '#0284C7',
    glyph: '⛵',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><polygon points="3 20 21 20 18 4 12 14 6 8"/></svg>'
  },
  {
    id: 'bondi-beach',
    name: 'Bondi Beach & Icebergs Pool',
    placeId: 'ChIJn5qtqpytEmsRn2juKNy2hjQ',
    lat: -33.8914755,
    lng: 151.2766845,
    altitude: 20,
    altitudeCorrection: 10,
    heading: 280,
    tilt: 58,
    camAltitude: 260,
    camRange: 1000,
    camTilt: 58,
    camHeading: 280,
    category: 'World-Famous Crescent Surf Beach',
    description: 'Australia’s legendary one-kilometer crescent of golden sand, renowned for surfing, coastal headland walks, and ocean pools.',
    highlights: ['Bondi Icebergs Ocean Saltwater Pool', 'Bondi to Coogee Coastal Walk', 'Pacific Ocean Surf Breaks'],
    iconName: 'beach',
    pinColor: '#F59E0B',
    glyph: '🏄',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M2 20c2-1 4-1 6 0s4 1 6 0 4-1 6 0"/><circle cx="12" cy="10" r="4"/></svg>'
  }
];

// -------------------------------------------------------------
// 9. AMSTERDAM LANDMARKS (Netherlands)
// -------------------------------------------------------------
export const LANDMARKS_AMSTERDAM: Landmark[] = [
  {
    id: 'van-gogh-museum',
    name: 'Van Gogh Museum',
    placeId: 'ChIJX1rTlu8JxkcRGsV8-a4oKMI',
    lat: 52.3584159,
    lng: 4.8810756,
    altitude: 30,
    altitudeCorrection: 15,
    heading: 340,
    tilt: 62,
    camAltitude: 200,
    camRange: 600,
    camTilt: 62,
    camHeading: 340,
    category: 'Modern Art Monographic Museum',
    description: 'Dedicated to the life and works of Vincent van Gogh, housing the world’s largest collection of his paintings including Sunflowers and Almond Blossom.',
    highlights: ['Sunflowers & The Bedroom Masterpieces', 'Kisho Kurokawa Modern Wing', 'Over 200 Van Gogh Original Paintings'],
    iconName: 'art',
    pinColor: '#EAB308',
    glyph: '🌻',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2"/></svg>'
  },
  {
    id: 'rijksmuseum',
    name: 'Rijksmuseum Amsterdam',
    placeId: 'ChIJ5Ra7we4JxkcRhYVAaq5zQ9U',
    lat: 52.3599976,
    lng: 4.8852188,
    altitude: 35,
    altitudeCorrection: 20,
    heading: 20,
    tilt: 62,
    camAltitude: 220,
    camRange: 650,
    camTilt: 62,
    camHeading: 20,
    category: 'Dutch National Art & History Museum',
    description: 'The grand Dutch national museum at Museumplein, designed by Pierre Cuypers, housing Rembrandt’s Night Watch and Vermeer masterpieces.',
    highlights: ['Rembrandt’s Masterpiece "The Night Watch"', 'Cuypers Gothic & Renaissance Facade', 'Museumplein Park & Reflecting Pond'],
    iconName: 'museum',
    pinColor: '#DC2626',
    glyph: '🎨',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M3 21h18M5 21V7l7-4 7 4v14M9 11v10M15 11v10"/></svg>'
  },
  {
    id: 'royal-palace-ams',
    name: 'Royal Palace of Amsterdam (Dam Square)',
    placeId: 'ChIJFQ6IwMYJxkcRis8dtZlOkTk',
    lat: 52.373169,
    lng: 4.891361,
    altitude: 35,
    altitudeCorrection: 20,
    heading: 110,
    tilt: 62,
    camAltitude: 220,
    camRange: 600,
    camTilt: 62,
    camHeading: 110,
    category: 'Dutch Golden Age City Hall & Palace',
    description: 'Originally built as Amsterdam’s city hall during the Dutch Golden Age in 1648 on Dam Square, later converted to a royal reception palace.',
    highlights: ['Dam Square Historic Public Center', 'Citizen’s Hall Atlas Marble Globe', 'Dutch Golden Age Classical Facade'],
    iconName: 'palace',
    pinColor: '#0284C7',
    glyph: '🏛️',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M3 21h18M5 21V7l7-4 7 4v14M9 11v10M15 11v10"/></svg>'
  },
  {
    id: 'westerkerk',
    name: 'Westerkerk & Jordaan Quarter',
    placeId: 'ChIJkyv4z8QJxkcR9FqUIxss0SM',
    lat: 52.3745,
    lng: 4.8837,
    altitude: 45,
    altitudeCorrection: 30,
    heading: 160,
    tilt: 62,
    camAltitude: 220,
    camRange: 600,
    camTilt: 62,
    camHeading: 160,
    category: 'Historic Renaissance Church & Tower',
    description: 'The 17th-century Protestant church featuring Amsterdam’s highest church tower (85m Westertoren), where Rembrandt was buried in 1669.',
    highlights: ['85-Meter Westertoren Bell Tower', 'Historic Jordaan Canal Quarter', 'Burial Place of Rembrandt van Rijn'],
    iconName: 'church',
    pinColor: '#10B981',
    glyph: '⛪',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M4 22V8l4-4 4 4v14M12 8l4-4 4 4v14M8 14h8v8H8z"/></svg>'
  },
  {
    id: 'anne-frank-house',
    name: 'Anne Frank House & Prinsengracht',
    placeId: 'ChIJSRE-IcUJxkcRCltjPmVdmtQ',
    lat: 52.375218,
    lng: 4.883977,
    altitude: 25,
    altitudeCorrection: 15,
    heading: 250,
    tilt: 64,
    camAltitude: 180,
    camRange: 550,
    camTilt: 64,
    camHeading: 250,
    category: 'Historic Canal House & Memorial',
    description: 'The 17th-century canal house on the Prinsengracht where Anne Frank hid during WWII and wrote her world-famous diary in the Secret Annex.',
    highlights: ['Secret Annex Bookcase Entrance', 'Prinsengracht Canal Ring Views', 'Westerkerk Church Belltower Nearby'],
    iconName: 'house',
    pinColor: '#8B5CF6',
    glyph: '📖',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20M4 4.5A2.5 2.5 0 0 1 6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15Z"/></svg>'
  }
];

// -------------------------------------------------------------
// 10. SINGAPORE LANDMARKS
// -------------------------------------------------------------
export const LANDMARKS_SINGAPORE: Landmark[] = [
  {
    id: 'buddha-tooth-temple',
    name: 'Buddha Tooth Relic Temple (Chinatown)',
    placeId: 'ChIJ0bwmznIZ2jEREOCMNggtIBk',
    lat: 1.2815,
    lng: 103.8443,
    altitude: 35,
    altitudeCorrection: 20,
    heading: 50,
    tilt: 62,
    camAltitude: 200,
    camRange: 550,
    camTilt: 62,
    camHeading: 50,
    category: 'Tang Dynasty Buddhist Temple & Museum',
    description: 'A monumental Tang Dynasty-style Buddhist temple in historic Chinatown housing what is believed to be the sacred tooth relic of the historical Buddha.',
    highlights: ['Tang Dynasty Architectural Stupa', 'Solid Gold Sacred Relic Chamber', 'Historic Chinatown Street Market'],
    iconName: 'temple',
    pinColor: '#EF4444',
    glyph: '⛩️',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M2 4h20M4 4v16M20 4v16M2 9h20M9 4v5M15 4v5"/></svg>'
  },
  {
    id: 'merlion-park',
    name: 'Merlion Park (Singapore Icon)',
    placeId: 'ChIJBTYg1g4Z2jERp_MBbu5erWY',
    lat: 1.2868,
    lng: 103.8545,
    altitude: 20,
    altitudeCorrection: 10,
    heading: 130,
    tilt: 62,
    camAltitude: 180,
    camRange: 600,
    camTilt: 62,
    camHeading: 130,
    category: 'National Mythical Mascot Fountain',
    description: 'The official mascot of Singapore, featuring the head of a lion and body of a fish spouting water over Marina Bay opposite the CBD towers.',
    highlights: ['Spouting 8.6-Meter Merlion Statue', 'Panoramic Waterfront Marina Views', 'Fullerton Heritage Waterfront Precinct'],
    iconName: 'lion',
    pinColor: '#D97706',
    glyph: '🦁',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><path d="M8 12a4 4 0 0 0 8 0"/></svg>'
  },
  {
    id: 'singapore-flyer',
    name: 'Singapore Flyer Giant Observation Wheel',
    placeId: 'ChIJzVHFNqkZ2jERboLN2YrltH8',
    lat: 1.2893,
    lng: 103.8631,
    altitude: 80,
    altitudeCorrection: 60,
    heading: 210,
    tilt: 60,
    camAltitude: 260,
    camRange: 700,
    camTilt: 60,
    camHeading: 210,
    category: 'Giant Observation Wheel',
    description: 'Standing 165 meters tall over Marina Bay, one of the world’s largest giant observation wheels with views spanning Singapore and neighboring islands.',
    highlights: ['165-Meter Panoramic Wheel', '28 Air-Conditioned Capsules', 'Views of F1 Singapore Street Circuit'],
    iconName: 'wheel',
    pinColor: '#8B5CF6',
    glyph: '🎡',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><path d="M12 2v20M2 12h20"/></svg>'
  },
  {
    id: 'marina-bay-sands',
    name: 'Marina Bay Sands',
    placeId: 'ChIJA5LATO4Z2jER111V-v6abAI',
    lat: 1.2834,
    lng: 103.8607,
    altitude: 150,
    altitudeCorrection: 130,
    heading: 240,
    tilt: 65,
    camAltitude: 380,
    camRange: 850,
    camTilt: 65,
    camHeading: 240,
    category: 'Integrated Resort & SkyPark',
    description: 'Moshe Safdie’s three cascading 55-story hotel towers topped by the cantilevered Sands SkyPark and the world’s longest rooftop infinity pool.',
    highlights: ['340m Sands SkyPark Cantilever', 'Rooftop Infinity Pool Over Skyline', 'Spectra Light & Water Show Bay'],
    iconName: 'resort',
    pinColor: '#0284C7',
    glyph: '🏨',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="2" width="16" height="20" rx="2"/></svg>'
  },
  {
    id: 'gardens-by-the-bay',
    name: 'Gardens by the Bay & Supertree Grove',
    placeId: 'ChIJMxZ-kwQZ2jERdsqftXeWCWI',
    lat: 1.2816,
    lng: 103.8636,
    altitude: 50,
    altitudeCorrection: 35,
    heading: 300,
    tilt: 60,
    camAltitude: 260,
    camRange: 800,
    camTilt: 60,
    camHeading: 300,
    category: 'Futuristic Horticultural Wonderland',
    description: 'A 250-acre nature park boasting iconic vertical garden Supertrees up to 50m tall, the Flower Dome, and Cloud Forest cooled conservatories.',
    highlights: ['Supertree Grove & OCBC Skyway', 'Cloud Forest Indoor Waterfall Dome', 'Garden Rhapsody Light & Sound Show'],
    iconName: 'garden',
    pinColor: '#10B981',
    glyph: '🌺',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2a6 6 0 0 0-6 6c0 3 2 5 6 12 4-7 6-9 6-12a6 6 0 0 0-6-6Z"/></svg>'
  }
];

// -------------------------------------------------------------
// 11. VENICE LANDMARKS (Italy)
// -------------------------------------------------------------
export const LANDMARKS_VENICE: Landmark[] = [
  {
    id: 'ponte-accademia',
    name: 'Ponte dell’Accademia (Grand Canal)',
    placeId: 'ChIJjYs6_dGxfkcRJYlQcj3fDKk',
    lat: 45.4317,
    lng: 12.3288,
    altitude: 25,
    altitudeCorrection: 15,
    heading: 65,
    tilt: 62,
    camAltitude: 180,
    camRange: 550,
    camTilt: 62,
    camHeading: 65,
    category: 'Wooden Arch Bridge & Iconic Vista',
    description: 'One of only four bridges over the Grand Canal, renowned for providing the quintessential postcard view looking east toward Santa Maria della Salute.',
    highlights: ['Classic Postcard View of Venice', 'Historic Wooden Arch Structure', 'Gallerie dell’Accademia Arts Hub'],
    iconName: 'bridge',
    pinColor: '#F59E0B',
    glyph: '🌉',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M2 18h20M4 18V8l8-5 8 5v10M8 12v6M16 12v6"/></svg>'
  },
  {
    id: 'santa-maria-salute',
    name: 'Basilica di Santa Maria della Salute',
    placeId: 'ChIJ241oDzOwfkcRXyfdym_t-ck',
    lat: 45.4307,
    lng: 12.3347,
    altitude: 35,
    altitudeCorrection: 20,
    heading: 40,
    tilt: 60,
    camAltitude: 220,
    camRange: 650,
    camTilt: 60,
    camHeading: 40,
    category: 'Baroque Octagonal Votive Basilica',
    description: 'The iconic domed Baroque basilica standing at the entrance to the Grand Canal, built in 1631 as a thanksgiving offering for deliverance from the plague.',
    highlights: ['Octagonal Istrian Stone Rotunda', 'Grand Canal Entrance Position', 'Paintings by Titian and Tintoretto'],
    iconName: 'basilica',
    pinColor: '#10B981',
    glyph: '🏛️',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2a4 4 0 0 0-4 4v16h8V6a4 4 0 0 0-4-4ZM4 12h16M2 22h20"/></svg>'
  },
  {
    id: 'rialto-bridge',
    name: 'Rialto Bridge (Ponte di Rialto)',
    placeId: 'ChIJOzqj-sexfkcRicyOKaERIHM',
    lat: 45.438,
    lng: 12.3359,
    altitude: 25,
    altitudeCorrection: 15,
    heading: 130,
    tilt: 62,
    camAltitude: 180,
    camRange: 550,
    camTilt: 62,
    camHeading: 130,
    category: 'Renaissance Stone Arch Bridge',
    description: 'The oldest of the four bridges spanning the Grand Canal, designed by Antonio da Ponte in 1591, lined with shops and bustling gondola traffic.',
    highlights: ['Grand Canal Central Panorama', '16th-Century Marble Stone Arch', 'Active Gondola & Vaporetto Waterway'],
    iconName: 'bridge',
    pinColor: '#0284C7',
    glyph: '🛶',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M2 18h20M4 18V8l8-5 8 5v10M8 12v6M16 12v6"/></svg>'
  },
  {
    id: 'doges-palace',
    name: 'Doge’s Palace & Bridge of Sighs',
    placeId: 'ChIJwdnQFACxfkcRMyKFAFEw_dw',
    lat: 45.4337,
    lng: 12.3404,
    altitude: 30,
    altitudeCorrection: 15,
    heading: 350,
    tilt: 62,
    camAltitude: 220,
    camRange: 600,
    camTilt: 62,
    camHeading: 350,
    category: 'Venetian Gothic Palace & Seat of Power',
    description: 'The historic residence of the Doge of Venice, featuring delicate pink Veronese marble arcades, the Chamber of the Great Council, and the Bridge of Sighs.',
    highlights: ['Bridge of Sighs Enclosed Marble Arch', 'Venetian Gothic Open Arcades', 'Grand Council Hall by Tintoretto'],
    iconName: 'palace',
    pinColor: '#EC4899',
    glyph: '🎭',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M3 21h18M5 21V7l7-4 7 4v14M9 11v10M15 11v10"/></svg>'
  },
  {
    id: 'st-marks-basilica',
    name: 'St. Mark’s Basilica & Piazza San Marco',
    placeId: 'ChIJv2xSZNexfkcRBaKsgyfVEgo',
    lat: 45.4344,
    lng: 12.3397,
    altitude: 30,
    altitudeCorrection: 15,
    heading: 30,
    tilt: 60,
    camAltitude: 220,
    camRange: 650,
    camTilt: 60,
    camHeading: 30,
    category: 'Italo-Byzantine Golden Cathedral',
    description: 'The opulent cathedral church on Piazza San Marco, famed for its shimmering gold mosaics, Byzantine domes, and the St. Mark’s Campanile bell tower.',
    highlights: ['Piazza San Marco Historic Center', 'Golden Interior Glass Mosaics', 'St Mark’s Soaring Brick Campanile'],
    iconName: 'basilica',
    pinColor: '#EAB308',
    glyph: '⛪',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M4 22V8l4-4 4 4v14M12 8l4-4 4 4v14M8 14h8v8H8z"/></svg>'
  }
];

// -------------------------------------------------------------
// 12. FLORENCE LANDMARKS (Italy)
// -------------------------------------------------------------
export const LANDMARKS_FLORENCE: Landmark[] = [
  {
    id: 'florence-duomo',
    name: 'Florence Cathedral (Brunelleschi’s Duomo)',
    placeId: 'ChIJHT2PyANUKhMR3HvodTCGwkE',
    lat: 43.7731,
    lng: 11.256,
    altitude: 70,
    altitudeCorrection: 55,
    heading: 120,
    tilt: 62,
    camAltitude: 280,
    camRange: 650,
    camTilt: 62,
    camHeading: 120,
    category: 'Renaissance Masterpiece Cathedral',
    description: 'Santa Maria del Fiore crowned by Filippo Brunelleschi’s revolutionary masonry dome, Giotto’s Campanile, and polychrome marble facade.',
    highlights: ['Brunelleschi’s Renaissance Red Tile Dome', 'Giotto’s Polychrome Marble Campanile', 'Baptistery of St. John Bronze Gates'],
    iconName: 'duomo',
    pinColor: '#EF4444',
    glyph: '⛪',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2v20M8 6h8M6 11h12M7 16h10M5 22h14"/></svg>'
  },
  {
    id: 'ponte-vecchio',
    name: 'Ponte Vecchio',
    placeId: 'ChIJZ7bcoqpWKhMR6ALnMOgKMUA',
    lat: 43.768,
    lng: 11.2532,
    altitude: 25,
    altitudeCorrection: 15,
    heading: 70,
    tilt: 62,
    camAltitude: 200,
    camRange: 600,
    camTilt: 62,
    camHeading: 70,
    category: 'Medieval Segmental Arch Bridge',
    description: 'The medieval closed-spandrel stone bridge over the Arno River, famous for jewelers’ shops perched along its edges and the elevated Vasari Corridor.',
    highlights: ['Vasari Corridor Secret Passage', 'Arno River Historic Reflections', 'Goldsmiths & Jewelers Workshops'],
    iconName: 'bridge',
    pinColor: '#D97706',
    glyph: '🌉',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M2 18h20M4 18V8l8-5 8 5v10M8 12v6M16 12v6"/></svg>'
  },
  {
    id: 'uffizi-gallery',
    name: 'Uffizi Gallery & Piazza della Signoria',
    placeId: 'ChIJgZDFjQBUKhMRzcTwm8i33s0',
    lat: 43.7678,
    lng: 11.2553,
    altitude: 30,
    altitudeCorrection: 15,
    heading: 340,
    tilt: 62,
    camAltitude: 220,
    camRange: 600,
    camTilt: 62,
    camHeading: 340,
    category: 'Premier Renaissance Art Museum',
    description: 'One of the world’s most prominent art museums, designed by Giorgio Vasari, housing Botticelli’s Birth of Venus, Leonardo da Vinci, and Michelangelo masterpieces.',
    highlights: ['Botticelli’s "The Birth of Venus"', 'Piazza della Signoria Sculpture Square', 'Palazzo Vecchio Medieval Fortress'],
    iconName: 'museum',
    pinColor: '#8B5CF6',
    glyph: '🎨',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M3 21h18M5 21V7l7-4 7 4v14M9 11v10M15 11v10"/></svg>'
  },
  {
    id: 'santa-croce',
    name: 'Basilica of Santa Croce',
    placeId: 'ChIJMcPMIwdUKhMRVRITnGR5go8',
    lat: 43.7686,
    lng: 11.2623,
    altitude: 35,
    altitudeCorrection: 20,
    heading: 100,
    tilt: 62,
    camAltitude: 220,
    camRange: 600,
    camTilt: 62,
    camHeading: 100,
    category: 'Franciscan Basilica & Temple of Italian Glories',
    description: 'The largest Franciscan church in the world, known as the Temple of the Italian Glories for housing the tombs of Michelangelo, Galileo, and Machiavelli.',
    highlights: ['Tombs of Michelangelo & Galileo Galilei', 'Giotto Frescoes in Bardi Chapel', 'Piazza Santa Croce Historic Square'],
    iconName: 'cathedral',
    pinColor: '#059669',
    glyph: '⛪',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M4 22V8l4-4 4 4v14M12 8l4-4 4 4v14M8 14h8v8H8z"/></svg>'
  },
  {
    id: 'piazzale-michelangelo',
    name: 'Piazzale Michelangelo Panorama',
    placeId: 'ChIJdRtQYPdTKhMRyamoDMkV3_8',
    lat: 43.7629,
    lng: 11.2650,
    altitude: 100,
    altitudeCorrection: 75,
    heading: 325,
    tilt: 58,
    camAltitude: 240,
    camRange: 750,
    camTilt: 58,
    camHeading: 325,
    category: 'Panoramic Hilltop Terrace & Belvedere',
    description: 'The famous hillside terrace south of the Arno offering the ultimate panoramic vista of Florence, Brunelleschi’s Duomo, and the Tuscan hills.',
    highlights: ['Sweeping Florence Skyline Panorama', 'Bronze Replica of Michelangelo’s David', 'Sunset Over the Arno River'],
    iconName: 'mountain',
    pinColor: '#0284C7',
    glyph: '🌅',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2"/></svg>'
  }
];

// -------------------------------------------------------------
// 13. RIO DE JANEIRO LANDMARKS (Brazil)
// -------------------------------------------------------------
export const LANDMARKS_RIO_DE_JANEIRO: Landmark[] = [
  {
    id: 'escadaria-selaron',
    name: 'Escadaria Selarón (Lapa Steps)',
    placeId: 'ChIJXWj-VXt_mQARNSwlewQeAXY',
    lat: -22.9154,
    lng: -43.1791,
    altitude: 35,
    altitudeCorrection: 20,
    heading: 210,
    tilt: 62,
    camAltitude: 200,
    camRange: 550,
    camTilt: 62,
    camHeading: 210,
    category: 'Vibrant Mosaic Staircase Monument',
    description: 'Jorge Selarón’s world-famous 215-step outdoor staircase connecting Lapa to Santa Teresa, decorated with over 2,000 colorful ceramic tiles from 60+ countries.',
    highlights: ['215 Decorated Ceramic Tile Steps', 'Bohemian Santa Teresa Gateway', 'Lapa Historic Arches Nearby'],
    iconName: 'art',
    pinColor: '#EF4444',
    glyph: '🎨',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M4 19L19 4M4 5l15 15M9 9l6 6"/></svg>'
  },
  {
    id: 'sugarloaf-mountain',
    name: 'Sugarloaf Mountain (Pão de Açúcar)',
    placeId: 'ChIJRfg5kECAmQARjLS837zXdYA',
    lat: -22.9486,
    lng: -43.1571,
    altitude: 396,
    altitudeCorrection: 30,
    heading: 240,
    tilt: 55,
    camAltitude: 550,
    camRange: 1100,
    camTilt: 55,
    camHeading: 240,
    category: 'Granite Monolith & Cable Car',
    description: 'A 396-meter granite monolith rising out of Guanabara Bay, accessible by the iconic glass-walled bondinho aerial cable car.',
    highlights: ['Bondinho Aerial Cable Car System', 'Guanabara Bay Oceanic Entry Point', 'Copacabana & Atlantic Ocean Panoramas'],
    iconName: 'mountain',
    pinColor: '#059669',
    glyph: '⛰️',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="m8 3 4 8 5-5 5 15H2L8 3z"/></svg>'
  },
  {
    id: 'christ-the-redeemer',
    name: 'Christ the Redeemer (Cristo Redentor)',
    placeId: 'ChIJP6FKmNV_mQAR3gKVAdeEyZ0',
    lat: -22.951916,
    lng: -43.210487,
    altitude: 710,
    altitudeCorrection: 45,
    heading: 70,
    tilt: 50,
    camAltitude: 1050,
    camRange: 1300,
    camTilt: 50,
    camHeading: 70,
    category: 'Art Deco Colossus Atop Corcovado',
    description: 'The 30-meter Art Deco statue of Jesus Christ created by Heitor da Silva Costa and Paul Landowski atop the 700-meter Corcovado mountain.',
    highlights: ['Corcovado 700-Meter Peak Panorama', 'Art Deco Soapstone Tile Construction', 'Guanabara Bay & Sugarloaf Vistas'],
    iconName: 'christ',
    pinColor: '#0284C7',
    glyph: '✝️',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="6" r="3"/><path d="M12 9v13M5 12h14"/></svg>'
  },
  {
    id: 'copacabana-beach',
    name: 'Copacabana Beach Promenade',
    placeId: 'ChIJa5WleUXVmwAR47P8r-4tEAo',
    lat: -22.9711,
    lng: -43.1822,
    altitude: 15,
    altitudeCorrection: 10,
    heading: 330,
    tilt: 58,
    camAltitude: 220,
    camRange: 900,
    camTilt: 58,
    camHeading: 330,
    category: 'Famous Wave-Pattern Beachfront',
    description: 'The world-renowned 4-kilometer crescent beach featuring Roberto Burle Marx’s black-and-white wave-pattern mosaic boardwalk promenade.',
    highlights: ['Burle Marx Portuguese Wave Mosaic', 'Forte de Copacabana Coastal Fort', 'Atlantic Oceanfront Culture'],
    iconName: 'beach',
    pinColor: '#F59E0B',
    glyph: '🏖️',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M2 20c2-1 4-1 6 0s4 1 6 0 4-1 6 0"/><circle cx="12" cy="10" r="4"/></svg>'
  },
  {
    id: 'ipanema-beach',
    name: 'Ipanema Beach & Arpoador',
    placeId: 'ChIJldwvQxvVmwARof3gMVPqHnI',
    lat: -22.9868,
    lng: -43.2030,
    altitude: 15,
    altitudeCorrection: 10,
    heading: 260,
    tilt: 58,
    camAltitude: 240,
    camRange: 950,
    camTilt: 58,
    camHeading: 260,
    category: 'Iconic Beach & Two Brothers Mountain View',
    description: 'Rio’s sophisticated coastal stretch famous for the song "The Girl from Ipanema," sunset watching at Arpoador rock, and views of Morro Dois Irmãos.',
    highlights: ['Pedra do Arpoador Sunset Spot', 'Morro Dois Irmãos Twin Peaks View', 'Posto 9 Cultural Beach Vibe'],
    iconName: 'beach',
    pinColor: '#8B5CF6',
    glyph: '🏄',
    svgIcon: '<svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#FFFFFF" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M2 20c2-1 4-1 6 0s4 1 6 0 4-1 6 0"/><circle cx="12" cy="10" r="4"/></svg>'
  }
];

// -------------------------------------------------------------
// COMPLETE CITIES CONFIGURATION (CALIBRATED COVERAGE BOUNDS)
// -------------------------------------------------------------
export const CITIES: CityConfig[] = [
  {
    id: 'haripur',
    name: 'Haripur (ہری پور)',
    country: 'Pakistan',
    flag: '🇵🇰',
    tagline: 'Gateway to Hazara & Land of Lakes',
    placeId: 'ChIJz2xY73Xn3jgR9-fH2bK_2xY',
    initialCam: {
      center: { lat: 33.9500, lng: 72.8800, altitude: 550 },
      range: 28000,
      tilt: 36,
      heading: 25
    },
    initialCamMobile: {
      center: { lat: 33.9500, lng: 72.8800, altitude: 550 },
      range: 36000,
      tilt: 28,
      heading: 25
    },
    landmarks: LANDMARKS_HARIPUR
  },
  {
    id: 'san-francisco',
    name: 'San Francisco',
    country: 'USA',
    flag: '🌉',
    tagline: 'Bay Area & Golden Gate',
    placeId: 'ChIJIQBpAG2ahYAR_6128GcTUEo',
    initialCam: {
      center: { lat: 37.7720, lng: -122.4350, altitude: 0 },
      range: 20000,
      tilt: 25,
      heading: 0
    },
    initialCamMobile: {
      center: { lat: 37.7720, lng: -122.4350, altitude: 0 },
      range: 26000,
      tilt: 18,
      heading: 0
    },
    landmarks: LANDMARKS_SAN_FRANCISCO
  },
  {
    id: 'tokyo',
    name: 'Tokyo',
    country: 'Japan',
    flag: '🗼',
    tagline: 'Metropolis of Neon & Tradition',
    placeId: 'ChIJ51cu8IcbXWARiRtXIothAS4',
    initialCam: {
      center: { lat: 35.6850, lng: 139.7550, altitude: 0 },
      range: 18000,
      tilt: 25,
      heading: 0
    },
    initialCamMobile: {
      center: { lat: 35.6850, lng: 139.7550, altitude: 0 },
      range: 24000,
      tilt: 18,
      heading: 0
    },
    landmarks: LANDMARKS_TOKYO
  },
  {
    id: 'paris',
    name: 'Paris',
    country: 'France',
    flag: '🏛️',
    tagline: 'City of Light & Monuments',
    placeId: 'ChIJD7fiBh9u5kcRYJSMaMOCCwQ',
    initialCam: {
      center: { lat: 48.8650, lng: 2.3250, altitude: 0 },
      range: 14000,
      tilt: 25,
      heading: 0
    },
    initialCamMobile: {
      center: { lat: 48.8650, lng: 2.3250, altitude: 0 },
      range: 18000,
      tilt: 18,
      heading: 0
    },
    landmarks: LANDMARKS_PARIS
  },
  {
    id: 'rome',
    name: 'Rome',
    country: 'Italy',
    flag: '🏛️',
    tagline: 'Eternal City & Classical Wonders',
    placeId: 'ChIJu46S-ZZhLxMROG5lkwZ3D7k',
    initialCam: {
      center: { lat: 41.8970, lng: 12.4730, altitude: 0 },
      range: 10000,
      tilt: 25,
      heading: 0
    },
    initialCamMobile: {
      center: { lat: 41.8970, lng: 12.4730, altitude: 0 },
      range: 14000,
      tilt: 18,
      heading: 0
    },
    landmarks: LANDMARKS_ROME
  },
  {
    id: 'new-york',
    name: 'New York City',
    country: 'USA',
    flag: '🗽',
    tagline: 'The City That Never Sleeps',
    placeId: 'ChIJOwg_06VPwokRYv534QaPC8g',
    initialCam: {
      center: { lat: 40.7350, lng: -74.0050, altitude: 0 },
      range: 19000,
      tilt: 25,
      heading: 0
    },
    initialCamMobile: {
      center: { lat: 40.7350, lng: -74.0050, altitude: 0 },
      range: 25000,
      tilt: 18,
      heading: 0
    },
    landmarks: LANDMARKS_NEW_YORK
  },
  {
    id: 'london',
    name: 'London',
    country: 'United Kingdom',
    flag: '🕰️',
    tagline: 'Royal Heritage & Thames Skyline',
    placeId: 'ChIJdd4hrwug2EcRmSrV3Vo6llI',
    initialCam: {
      center: { lat: 51.5040, lng: -0.1080, altitude: 0 },
      range: 12000,
      tilt: 25,
      heading: 0
    },
    initialCamMobile: {
      center: { lat: 51.5040, lng: -0.1080, altitude: 0 },
      range: 16000,
      tilt: 18,
      heading: 0
    },
    landmarks: LANDMARKS_LONDON
  },
  {
    id: 'barcelona',
    name: 'Barcelona',
    country: 'Spain',
    flag: '🏰',
    tagline: 'Modernisme & Mediterranean Charm',
    placeId: 'ChIJ5TCOcRaYpBIRCmZHTz37sEQ',
    initialCam: {
      center: { lat: 41.4020, lng: 2.1680, altitude: 0 },
      range: 11000,
      tilt: 25,
      heading: 0
    },
    initialCamMobile: {
      center: { lat: 41.4020, lng: 2.1680, altitude: 0 },
      range: 15000,
      tilt: 18,
      heading: 0
    },
    landmarks: LANDMARKS_BARCELONA
  },
  {
    id: 'sydney',
    name: 'Sydney',
    country: 'Australia',
    flag: '⛵',
    tagline: 'Harbour City & Sunlit Beaches',
    placeId: 'ChIJP3Sa8ziYEmsRUKgyFmh9AQM',
    initialCam: {
      center: { lat: -33.8700, lng: 151.2380, altitude: 0 },
      range: 15000,
      tilt: 25,
      heading: 0
    },
    initialCamMobile: {
      center: { lat: -33.8700, lng: 151.2380, altitude: 0 },
      range: 20000,
      tilt: 18,
      heading: 0
    },
    landmarks: LANDMARKS_SYDNEY
  },
  {
    id: 'amsterdam',
    name: 'Amsterdam',
    country: 'Netherlands',
    flag: '🚲',
    tagline: 'Historic Canals & Golden Age Art',
    placeId: 'ChIJVXealLU_xkcRja_At0z9AGY',
    initialCam: {
      center: { lat: 52.3670, lng: 4.8870, altitude: 0 },
      range: 7000,
      tilt: 25,
      heading: 0
    },
    initialCamMobile: {
      center: { lat: 52.3670, lng: 4.8870, altitude: 0 },
      range: 9500,
      tilt: 18,
      heading: 0
    },
    landmarks: LANDMARKS_AMSTERDAM
  },
  {
    id: 'singapore',
    name: 'Singapore',
    country: 'Singapore',
    flag: '🌆',
    tagline: 'Garden City in a Futuristic Bay',
    placeId: 'ChIJdZOLiiMR2jERxPWrUs9peIg',
    initialCam: {
      center: { lat: 1.2850, lng: 103.8580, altitude: 0 },
      range: 6000,
      tilt: 25,
      heading: 0
    },
    initialCamMobile: {
      center: { lat: 1.2850, lng: 103.8580, altitude: 0 },
      range: 8500,
      tilt: 18,
      heading: 0
    },
    landmarks: LANDMARKS_SINGAPORE
  },
  {
    id: 'venice',
    name: 'Venice',
    country: 'Italy',
    flag: '🎭',
    tagline: 'Queen of the Adriatic & Canals',
    placeId: 'ChIJiT3W8dqxfkcRLxCSvfDGo3s',
    initialCam: {
      center: { lat: 45.4350, lng: 12.3350, altitude: 0 },
      range: 5000,
      tilt: 25,
      heading: 0
    },
    initialCamMobile: {
      center: { lat: 45.4350, lng: 12.3350, altitude: 0 },
      range: 7000,
      tilt: 18,
      heading: 0
    },
    landmarks: LANDMARKS_VENICE
  },
  {
    id: 'florence',
    name: 'Florence',
    country: 'Italy',
    flag: '🎨',
    tagline: 'Cradle of the Renaissance',
    placeId: 'ChIJrdbSgKZWKhMRAyrH7xd51ZM',
    initialCam: {
      center: { lat: 43.7680, lng: 11.2590, altitude: 0 },
      range: 5000,
      tilt: 25,
      heading: 0
    },
    initialCamMobile: {
      center: { lat: 43.7680, lng: 11.2590, altitude: 0 },
      range: 7000,
      tilt: 18,
      heading: 0
    },
    landmarks: LANDMARKS_FLORENCE
  },
  {
    id: 'rio-de-janeiro',
    name: 'Rio de Janeiro',
    country: 'Brazil',
    flag: '⛰️',
    tagline: 'Marvelous City & Coastal Peaks',
    placeId: 'ChIJW6AIkVXemwARTtIvZ2xC3FA',
    initialCam: {
      center: { lat: -22.9500, lng: -43.1850, altitude: 0 },
      range: 16000,
      tilt: 25,
      heading: 0
    },
    initialCamMobile: {
      center: { lat: -22.9500, lng: -43.1850, altitude: 0 },
      range: 22000,
      tilt: 18,
      heading: 0
    },
    landmarks: LANDMARKS_RIO_DE_JANEIRO
  }
];
